### ISSUE TITLE
Selectable 针对3.0.8 版本有变动对吗 

### ISSUE THREAD

**Issue by HubertBiyo** [dotnetcore/DotnetSpider#101]
如题，和原来的用法不一样了

**Comment by zlzforever** [comment]
是的。有一个比较大的设计变化，各个部件解藕成单独组件了。参考Sample下面的例子使用。

**Comment by HubertBiyo** [comment]
> 是的，有一个比较大的设计变化，各个部件解藕成单独组件了。参考示例下面的例子使用。

好的，谢谢
