### ISSUE TITLE
 部署到Centos7.3 运行时提示 CommandLineParser 没有找到的错误。

### ISSUE THREAD

**Issue by sxlvalue** [dotnetcore/DotnetSpider#103]
我的开发版本是dotnet core 2.1在centos 7.3中安装了dotnet core 2.1，程序在windows上运行正常，拷贝到linux上运行，报出如下错误，是哪里需要设置吗。我看DotnetSpider貌似是跨平台的啊！

An assembly specified in the application dependencies manifest (XXXX.deps.json) was not found:
    package: 'CommandLineParser', version: '2.3.0'
    path: 'lib/netstandard1.5/CommandLine.dll'

**Comment by sanjusss** [comment]
要先用dotnet publish命令生成发行版。详细参数见msdn文档。

**Comment by sxlvalue** [comment]
我的编译有问题，学艺不精，以为linux和windows一样的编译就行。
在linux下运行，需要到项目根目录运行：dotnet publish -c Release
然后把Release目录里的publish下的dll全都拷贝到linux中执行dotnet xxx.dll就可以了
