### ISSUE TITLE
抓取网址的时候，多次跳转的，如何获得最后的URL

### ISSUE THREAD

**Issue by ufidazf** [dotnetcore/DotnetSpider#108]
从页面上获得的地址如下： https://go.smzdm.com/f64527544ec722a5/ca_aa_fx_95_13199497_11002_3039_1635_0
跳转后 地址
https://detail.tmall.com/item.htm?id=583792709730&ali_trackid=2:mm_25282911_3455987_64928250081:1553669154_174_533697660
如何转换成后面的地址呢？

**Comment by zlzforever** [comment]
1. 原理：跳转是服务端返回302，客户端于是做跳转。如果你不请求server端，较难猜出跳转逻辑。
2. 解决方式: 你并不需要知道目标链接，HttpClient 可以 开启 AutoRedirect, 或者自己写一个 Handler 做跳转，参考代码: https://github.com/dotnetcore/DotnetSpider/blob/master/src/DotnetSpider/Core/GlobalRedirectHandler.cs
