### ISSUE TITLE
oracle数据库

### ISSUE THREAD

**Issue by strongzs** [dotnetcore/DotnetSpider#109]
希望可以支持oracle的数据管道，或者开放TableInfo类的IsAutoIncrementPrimary属性的保护级别为public，这样可以自定义实现

**Comment by zlzforever** [comment]
@strongzs 我在设计全新的完全基于分布式考虑的框架。如果你有兴趣可以参与进来写oracle的存储

**Comment by strongzs** [comment]
好的，我非常有兴趣，主要是还没参与过开源的项目，而且爬虫也刚接触，希望大佬多多指点
