### ISSUE TITLE
 运行Sample时，Spider.cs/OnComplete()抛出NullReferenceException

### ISSUE THREAD

**Issue by DingpingZhang** [dotnetcore/DotnetSpider#11]
- windows 10 enterprise
- visual studio 2017
- .NETCoreApp 1.1

运行`DotnetSpider.Smple/BaseUsage.CustmizeProcessorAndPipeline();`：
![snipaste20170428_083850](https://cloud.githubusercontent.com/assets/8541016/25509947/1e67fc74-2bef-11e7-8371-4842bd19ded4.png)

随后我在全局查找了`OnComplete`字段，发现并没有被注册：
![snipaste20170428_084942](https://cloud.githubusercontent.com/assets/8541016/25509999/9feeb332-2bef-11e7-80b5-b7ce63a837ee.png)

是否考虑改为：`OnCompleted?.Invoke()`？

**Comment by zlzforever** [comment]
是的,  最近一两周在重构，可能会有蛮多问题:)  谢谢



zlzforever@163.com
 
发件人： Dingping Zhang
发送时间： 2017-04-28 08:52
收件人： zlzforever/DotnetSpider
抄送： Subscribed
主题： [zlzforever/DotnetSpider] 运行Sample时，Spider.cs/OnComplete()抛出NullReferenceException (#11)
windows 10 enterprise
visual studio 2017
.NETCoreApp 1.1
随后我在全局查找了OnComplete字段，发现并没有被注册：
是否考虑改为：OnCompleted?.Invoke()？

**Comment by zlzforever** [comment]
fixed
