### ISSUE TITLE
4.0版本如何进行限速？

### ISSUE THREAD

**Issue by JadynWong** [dotnetcore/DotnetSpider#111]
之前3.0版本 使用单线程 + AfterDownloadCompleteHandler 内 随机睡眠 ，4.0不知道从哪下手

**Comment by JadynWong** [comment]
有一个Speed属性，是固定限速

**Comment by zlzforever** [comment]
1.  新版本因为下载器是分布式的。所以不能以单机的思路去思考问题。所有的请求分发到上百个下载器，本身下载顺序，间隔就无法控制，因此随机睡眠是否有意义？
2. 所有的请求会先发到下载中心，下载中心依据策略(还未实现)分发到各下载器。比如 Request1 从下载器1下载的，则生成的 targetRequest 也必须回到那个下载器。或者如你想要的停随机停顿。

如果你有时间和兴趣可以交给你来实现请求的分发策略。

**Comment by JadynWong** [comment]
@zlzforever 谢谢邀请，分布式的话，还没有太好的思路，如果有思路会pr的
