### ISSUE TITLE
请教WebDriver设置可以调用IE吗？

### ISSUE THREAD

**Issue by MetSystem** [dotnetcore/DotnetSpider#113]
爬的页面带OCX控件，目标数据需要在ocx加载完成后才能获取到。

**Comment by MetSystem** [comment]
我看 https://github.com/dotnetcore/DotnetSpider/blob/6e748ed885833e9ef850bf3db3480d5de0626bd3/src/DotnetSpider/Downloader/DownloaderAllocator.cs
70行
case DownloaderType.WebDriver:
	{
	         throw new NotImplementedException();
	}

这个没实现吗？

**Comment by zlzforever** [comment]
在实现全新的设计。webdriver要放到最后来搞

**Comment by MetSystem** [comment]
👍

**Comment by MetSystem** [comment]
全新设计大概会什么时间发布

**Comment by zlzforever** [comment]
预计6月底。就缺一个Portal了（没写完）

**Comment by ImagineL** [comment]
已经八月啦...

**Comment by ysqopen** [comment]
哎，上错船了。原来 C#的爬虫这么弱：连个js都搞不掂。这也叫爬虫？这样的功能也有人用？
