### ISSUE TITLE
上生产环境，运行几次后，任务管理器驻留了大量进程，无法释放，造成服务器资源吃完了。有见过的吗，是否需要手动释放资源？

### ISSUE THREAD

**Issue by ufidazf** [dotnetcore/DotnetSpider#114]
![image](https://user-images.githubusercontent.com/48978611/56087294-8cb29880-5e9a-11e9-9268-5f3ac0978dc6.png)

**Comment by ufidazf** [comment]
此时程序已经运行完毕了，这些进程就挂在这里了。。。

**Comment by zlzforever** [comment]
新版本我还没有去实现 webdriver 的下载器，后面会有计划实现 webdriver pool。老版本的话需要你自己去 DEBUG 一下看在 WebDriverDownloader 里面有没有 dispose 这个 driver

**Comment by ufidazf** [comment]
好像 taskkill进程可以解决，目前还在监控，看情况。

**Comment by sanjusss** [comment]
webdriver调用Chrome的日常，我不用DotnetSpider时也经常出现这个问题。
我当时是用docker运行chrome的，定时重启容器解决。
Windows上只能靠结束进程了。

如果是短时间内生成的大量进程，说明代码里没有即时释放webdriver，需要对代码进行检查。
