### ISSUE TITLE
EntitySpider示例，使用SQL Server存储，爬虫插入数据时SQL报错

### ISSUE THREAD

**Issue by YuZhiCaptain** [dotnetcore/DotnetSpider#116]
**用Example中的EntitySpider 爬CnBlog时，程序自动创建的表会报错，错误内容如下：**
尝试插入数据失败: System.Data.SqlClient.SqlException (0x80131904): 不能将值 NULL 插入列 'website'，表 'cnblogs.dbo.cnblogs_entity_model'；列不允许有 Null 值。INSERT 失败。
语句已终止。

**Comment by free12500540** [comment]
把这个列剔除出索性列即可。

**Comment by free12500540** [comment]
68行 HasIndex(x => new {x.WebSite, x.Guid}, true)改为HasIndex(x => new {x=>{}x.Guid}, true)

**Comment by zlzforever** [comment]
已修复
