### ISSUE TITLE
有教程吗？

### ISSUE THREAD

**Issue by tiger2014** [dotnetcore/DotnetSpider#117]

**Comment by zlzforever** [comment]
新设计是完全的重写。可以参考Sample项目里的例子学习

**Comment by imba-tjd** [comment]
![图片](https://user-images.githubusercontent.com/24759802/57683896-3a19f700-7667-11e9-9a95-cac7bf605224.png)

@zlzforever wiki里上面这一部分需要去掉，还需要写一下要加哪些using。不然真的是例子都跑不起来……

然后运行起来后貌似会添加上千个任务……

**Comment by zlzforever** [comment]
@imba-tjd 因为重新设计了。这种老的API是完全没有了。如果要学习先从Sample项目里的例子学起，抄一抄没那么难的。

**Comment by imba-tjd** [comment]
那个页面已经更新过了，但是没有删掉老的。

**Comment by yang-xiaodong** [comment]
Duplicate of #77 

关闭此issue，以便于在同一个会话中讨论...
