### ISSUE TITLE
在new Request中自定义的property，通过在实体字段上添加 SelectorType.Enviroment特性，获取不到值

### ISSUE THREAD

**Issue by hechao0220** [dotnetcore/DotnetSpider#119]
在EntitySpider示例代码中，在构造请求时，自定义了new Dictionary<string, string> {{"网站", "博客园"}}，后面实体字段如下获取值，
[Required]
			[StringLength(200)]
			[ValueSelector(Expression = "网站", Type = SelectorType.Enviroment)]
			public string WebSite { get; set; }

但是执行完后，数据库表中字段WebSite还是为空，调试时发现，context.Response.Request.GetProperties()没有了自定义的property了，
这是不是个bug呢？

**Comment by rasikas** [comment]
I think I have the same issue, and mentioned in #124
