### ISSUE TITLE
多个url重复匹配所有的Processor？

### ISSUE THREAD

**Issue by itotaku-tm** [dotnetcore/DotnetSpider#122]
我想爬取多个网站，配置多个url以及对应的Processor。调试的时候发现，每一个url都会去匹配所有的Processor。这种情况效率很慢，能不能让一个url就只是对应一个Processor？
是我的写法有问题，还是有办法进行解决呢？

**Comment by zlzforever** [comment]
老的 Processor里和 新的Parser里都可以添加正则判断。

**Comment by itotaku-tm** [comment]
谢谢，这个问题已经解决
