### ISSUE TITLE
Request properties retrieved from the DataParsers

### ISSUE THREAD

**Issue by rasikas** [dotnetcore/DotnetSpider#124]
Thanks for the wonderful library, however it is really hard to understand how it works due to lack of English comments, It would be great if you could add the log info in English.
My question is about the Request properties. My understanding is we can add the `Request` properties and then they can be accessed in any other `DataParser`'s `context.Respose.Request.GetProperties()` 

When I try one of your samples it always gives the empty collection.
Sample I use is 
https://github.com/dotnetcore/DotnetSpider/blob/master/src/DotnetSpider.Sample/samples/BaseUsage.cs#L27

and I simply add a sample property, but I cannot access it in the DataParser.
Please refer the image below in debug mode.

![image](https://user-images.githubusercontent.com/1381205/59728999-ba8fd100-927f-11e9-800f-1d4ad192a947.png)

How do we pass set of custom properties from the initial Spider request to the DataFlow handlers

Thank you

**Comment by zlzforever** [comment]
It's a issue cause _properties is private in Request, will fix today.

**Comment by rasikas** [comment]
Thank you

**Comment by zlzforever** [comment]
4.0.7

**Comment by rasikas** [comment]
Looks like 4.0.4 to 4.0.7 is not a minor defect change, I updated the library to 4.0.7 and all the namespaces have been changed and some properties removed from classes, that's a big change. So I reverted back to 4.0.4. It would be great if you change the versions properly. Thank you
