### ISSUE TITLE
能不能使用API接口返回数据

### ISSUE THREAD

**Issue by itotaku-tm** [dotnetcore/DotnetSpider#129]
请问下，如果我想通过webAPI来返回爬取的数据。在BasePipeline中如何返回数据给调用者，或者爬虫有提供这种返回爬取数据的方式吗？
因为爬虫内部都是通过继承接口来实现的方法，只有一层层数据向下传递的。有没有在爬取完后，能向上返回结果的？或者能怎么实现，能提供下思路嘛

**Comment by zlzforever** [comment]
你是指 先通过一个接口查询到如某些 ID 列表，然后再通过另一个接口专入ID获得详细信息这种模式吗？

**Comment by itotaku-tm** [comment]
是我自己没理解透，后面研究了下，搞定了。3Q
