### ISSUE TITLE
关于httpclient下载器对uri中#号网址无法抓取

### ISSUE THREAD

**Issue by free12500540** [dotnetcore/DotnetSpider#130]
![#号问题1](https://user-images.githubusercontent.com/32448600/61014036-01bd3d80-a3b8-11e9-8f31-ec7baef74bd0.jpg)
![#号问题](https://user-images.githubusercontent.com/32448600/61014039-041f9780-a3b8-11e9-9af7-db6aa34f24a0.jpg)
如图所示，抓取页面遇到#号就会出现问题，从URL匹配器开始追踪，最终发现问题出现在httpclientDownloader处，目前已捕获该错误。if (response.TargetUrl.Contains("#"))
			{
				var i = 1;
			}是自定义编码捕获错误的
修复思路：从匹配器那使用 split('#'),丢弃#号及其后面的uri信息
![#号问题（修复）](https://user-images.githubusercontent.com/32448600/61014718-65953580-a3bb-11e9-977c-3caeff87eeeb.jpg)

**Comment by free12500540** [comment]
版本是release 3.1.0的，最新版代码未做测试

**Comment by zlzforever** [comment]
@free12500540  3.1.0的版本太老，新版本是全新设计的。不确定是否也有这样的问题，是否可以帮助分析一下。

**Comment by free12500540** [comment]
ok,等新版本稳定后，我把环境迁移过来

**Comment by free12500540** [comment]
@zlzforver 最新版也发现这个问题。目前处理办法还是除#
