### ISSUE TITLE
关于中文编码GB2312类，自动获取失败的问题

### ISSUE THREAD

**Issue by free12500540** [dotnetcore/DotnetSpider#132]
![image](https://user-images.githubusercontent.com/32448600/61755827-e3aa0100-adeb-11e9-896c-13b8a520d8e1.png)
如上图所示，中文网页编码一旦遇到双meta元素标签的，就无法识别charset，导致变为默认utf编码格式造成乱码。目前正在线上运行，已发现多起故障，追踪代码，发现是此处正则解析有问题
![image](https://user-images.githubusercontent.com/32448600/61756104-07217b80-aded-11e9-84f4-de9663369cac.png)
目前正在进一步测试，以发现问题所在

**Comment by zlzforever** [comment]
@free12500540 编码问题确实比较难办，没有 100% 准确的方法。所以在 Request 里可以自己设计解读编码。

**Comment by zlzforever** [comment]
@free12500540 新版本 downloader 不再负责解码了。下载的内容会以byte[]形式通过消息队列传回爬虫实例做处理，你可以在你的 parser里做你任何想做的操作：比如解压、解码

**Comment by RockNHawk** [comment]
我记得 .NET 有一个编码检测库的，以前用过，很棒，可以用那个库探测一下编码类型，再解码。

**Comment by zlzforever** [comment]
HttpClient 的 ReadAsStringAsync 有一定的检测能力，但我没有确认是否能够完全检测。
@RockNHawk 请问是哪个库可以检测编码？

**Comment by RockNHawk** [comment]
@zlzforever 
NChardet，https://www.nuget.org/packages/NChardet/
很老的一个库了，这个似乎是别人 fork 之后维护的版本，我多年以前就用的这个，挺准的。

另外附上一段从我以前的程序反编译出来调用这个库的代码，这个方法会先快速探测是不是 UTF8 或 Unicode，不行再调用 NChardet，开销更小。


    using System;
    using System.IO;
    using System.Text;
    using NChardet;

    namespace SwordFile
    {
        public class GetEncodingType
        {
            public static Encoding GetEncodingOfFile(string filename)
            {
                byte[] array;
                int aLen;
                using (FileStream fileStream = new FileStream(filename, FileMode.Open, FileAccess.Read))
                {
                    array = new byte[fileStream.Length];
                    aLen = fileStream.Read(array, 0, array.Length);
                }
                if (array.Length > 2 && array[0] == 239 && array[1] == 187 && array[2] == 191)
                {
                    return Encoding.UTF8;
                }
                if (array.Length >= 2 && array[0] == 255 && array[1] == 254)
                {
                    if (array.Length >= 4 && array[2] == 0 && array[3] == 0)
                    {
                        return Encoding.UTF32;
                    }
                    return Encoding.Unicode;
                }
                else
                {
                    if (array.Length >= 2 && array[0] == 254 && array[1] == 255)
                    {
                        return Encoding.BigEndianUnicode;
                    }
                    if (array.Length >= 4 && array[0] == 0 && array[1] == 0 && array[2] == 254 && array[3] == 255)
                    {
                        return Encoding.GetEncoding("UTF-32BE");
                    }
                    MyCharsetDetectionObserver myCharsetDetectionObserver = new MyCharsetDetectionObserver();
                    Detector detector = new Detector();
                    detector.Init(myCharsetDetectionObserver);
                    if (detector.isAscii(array, aLen))
                    {
                        return Encoding.ASCII;
                    }
                    detector.DoIt(array, aLen, false);
                    detector.Done();
                    if (string.IsNullOrEmpty(myCharsetDetectionObserver.Charset))
                    {
                        return Encoding.Default;
                    }
                    return Encoding.GetEncoding(myCharsetDetectionObserver.Charset);
                }
            }
        }
    }

**Comment by zlzforever** [comment]
那看来不需要做特别处理了，现在的 HttpContent 有默认编码检测：
 private static bool TryDetectEncoding(
      ArraySegment<byte> buffer,
      out Encoding encoding,
      out int preambleLength)
    {
      byte[] array = buffer.Array;
      int offset = buffer.Offset;
      int count = buffer.Count;
      if (count >= 2)
      {
        switch ((int) array[offset] << 8 | (int) array[offset + 1])
        {
          case 61371:
            if (count >= 3 && array[offset + 2] == (byte) 191)
            {
              encoding = Encoding.UTF8;
              preambleLength = 3;
              return true;
            }
            break;
          case 65279:
            encoding = Encoding.BigEndianUnicode;
            preambleLength = 2;
            return true;
          case 65534:
            if (count >= 4 && array[offset + 2] == (byte) 0 && array[offset + 3] == (byte) 0)
            {
              encoding = Encoding.UTF32;
              preambleLength = 4;
            }
            else
            {
              encoding = Encoding.Unicode;
              preambleLength = 2;
            }
            return true;
        }
      }
      encoding = (Encoding) null;
      preambleLength = 0;
      return false;
    }

**Comment by RockNHawk** [comment]
这个能判断 GB2312 嘛，NChardet 会检测 GB2312，GB1803 等等。。。
