### ISSUE TITLE
上生产环境后出现这个错误：OnExceptionOnStart The configured user limit (128) on the number of inotify instances has been reached.

### ISSUE THREAD

**Issue by hechao0220** [dotnetcore/DotnetSpider#134]
调用方式如下：
public static async Task RunAsync()
        {
            var toutiaoSpider = Spider.Create<ToutiaoSpider>();
            await toutiaoSpider.RunAsync();
            var fangHuSpider = Spider.Create<FangHuSpider>();
            await fangHuSpider.RunAsync();
            var eastmoneySpider = Spider.Create<EastmoneySpider>();
            await eastmoneySpider.RunAsync();
        }
在网上搜了下，说是读取json文件并提供监视造成的。
这是不是个bug？

**Comment by zlzforever** [comment]
@neil-he 在 docker 环境下运行吗？

**Comment by hechao0220** [comment]
@zlzforever 不是的，是直接部署在centos7上的
