### ISSUE TITLE
关于使用隧道代理的问题？

### ISSUE THREAD

**Issue by itotaku-tm** [dotnetcore/DotnetSpider#139]
你好：
     我在使用爬虫的时候，前段时间使用API接口地址，返回代理IP，然后实现爬虫接口使用代理。这样没问题
    这两天我公司换了一个代理模式，使用隧道代理，接口不在返回代理IP了。框架原有的接口无法实现代理了。启用这个UseSpecifiedUriWebProxy，可以传入代理IP，端口，用户名，密码。但是测试发现也不能实现代理
   查看源码后，我直接在IHttpClientPool中的Init方法，把代理信息写死，然后生成后的Dll替换了NUGet下载的DLL。才可以使用正常代理。但是这样很不方便，后期维护很麻烦，请问下UseSpecifiedUriWebProxy这块要怎么使用呢？
我使用的爬虫版本比较旧，是2.5.0的，在新版本中，这个问题有解决吗

**Comment by landonzeng** [comment]
@itotaku-tm 兄弟，这个框架怎么使用代理ip啊？方便发个demo上来么？一直不知道怎么用ip代理

**Comment by itotaku-tm** [comment]
最近好久我也没用这套框架了，但是不是那么好用。如果只是针对单个网站的爬取还行。但如果是对多个网站，或者多级爬取就不是很方便了
我自己尝试这去理解，修改过这套框架，在多线程情况下，感觉都不方便，特别是几个类之间数据的传递
现在手上也没有DOMO的，已经放弃
如果你是对单网站进行爬取，去下载作者的代码，稍微看下，修改下就能用了



在 2019-12-20 17:11:28，"landon" <notifications@github.com> 写道：

@itotaku-tm 兄弟，这个框架怎么使用代理ip啊？方便发个demo上来么？一直不知道怎么用ip代理

**Comment by landonzeng** [comment]
@itotaku-tm 好的，谢谢兄弟了，对了，有什么好的抓爬框架推荐的么？

**Comment by itotaku-tm** [comment]
没去找了，没有相关爬取需求了，而且感觉去理解一套要修改的框架，花费的时间成本太高了



在 2020-01-02 15:42:20，"landon" <notifications@github.com> 写道：

@itotaku-tm 好的，谢谢兄弟了，对了，有什么好的抓爬框架推荐的么？

**Comment by zlzforever** [comment]
嗯，这是我的问题，抱歉。新的 5.0 版本，还在分支中，已经解决了代理的所有问题。
