### ISSUE TITLE
XPath选择时出现与浏览器复制的XPath不一致问题

### ISSUE THREAD

**Issue by gmono** [dotnetcore/DotnetSpider#157]
测试网页
http://ren.bytravel.cn/history/wanganshi.html
使用ChromeWebDriver下载器（自己实现），经测试得到的RawText与原网页浏览器解析后的Dom结构一致

目的Node，红字人名
Firefox复制XPath和Chrome复制full XPath结果均为
/html/body/div[3]/div[1]/div[2]/h1
在程序中使用会复制错误，需要使用
/html/body/div[2]/div[1]/div[2]/h1

chrome直接复制XPath得到的//*[@id=\"page_left\"]/div[2]/h1  测试正常
CSS选择器
#page_left > div:nth-child(2) > h1:nth-child(1) 正常

CSS路径
html body div#pagebody div#page_left div h1
在Firefox和Chrome上测试均正常，在爬虫中测试无法选择（结果null）

这个页面中可能存在的不标准的地方有 ：
    页面中存在多个id为pagebody的div并列
是否是Html Agility Pack容错性问题？

**Comment by zlzforever** [comment]
因为HttpClient下载的纯HTML, 而 ChromeDriver, Firefox 是执行过 JS 的结果
