### ISSUE TITLE
请问这是一个以支持搜索式的通用爬虫为目标的爬虫吗？

### ISSUE THREAD

**Issue by RockNHawk** [dotnetcore/DotnetSpider#160]
你好，

我看到首页给的示例，通过AddRequests 添加了两个列表页，我想请问，爬虫是否能够根据给定一个种子 URL，然后自动分析并爬取这个 URL 的全站页面呢？

谢谢～

**Comment by RockNHawk** [comment]
我看到了，支持的，在这里 https://github.com/dotnetcore/DotnetSpider/blob/master/src/DotnetSpider.Sample/samples/WholeSiteSpider.cs

    using System;
    using System.Threading.Tasks;
    using DotnetSpider.Common;
    using DotnetSpider.DataFlow;
    using DotnetSpider.DataFlow.Parser;
    using DotnetSpider.DataFlow.Storage;
    using DotnetSpider.Downloader;
    using Microsoft.Extensions.Configuration;
    using Serilog;

    namespace DotnetSpider.Sample.samples
    {
        public class WholeSiteSpider
        {
            public static void Run1()
            {
                var builder = new SpiderHostBuilder()
                    .ConfigureLogging(x => x.AddSerilog())
                    .ConfigureAppConfiguration(x => x.AddJsonFile("appsettings.json"))
                    .ConfigureServices(services =>
                    {
                        services.AddThroughMessageQueue();
                        services.AddLocalDownloadCenter();
                        services.AddDownloaderAgent(x =>
                        {
                            x.UseFileLocker();
                            x.UseDefaultAdslRedialer();
                            x.UseDefaultInternetDetector();
                        });
                        services.AddStatisticsCenter(x => x.UseMemory());
                    });

                var provider = builder.Build();
                var spider = provider.Create<Spider>();

                spider.Id = Guid.NewGuid().ToString("N"); // 设置任务标识
                spider.Name = "博客园全站采集"; // 设置任务名称
                spider.Speed = 1; // 设置采集速度, 表示每秒下载多少个请求, 大于 1 时越大速度越快, 小于 1 时越小越慢, 不能为0.
                spider.Depth = 3; // 设置采集深度
                var parser = new DataParser
                {
                    SelectableBuilder = context => context.Response.ToSelectable(ContentType.Html),
                    Required = DataParserHelper.CheckIfRequiredByRegex("cnblogs\\.com")
                };
                parser.SetFollowRequestQuerier(DataParserHelper.QueryFollowRequestsByXPath("."));
                spider.AddDataFlow(parser).AddDataFlow(new ConsoleStorage()); // 控制台打印采集结果
                spider.AddRequests("http://www.cnblogs.com/"); // 设置起始链接
                spider.RunAsync().GetAwaiter().GetResult(); // 启动
            }

            public static Task Run2()
            {
                var builder = new SpiderHostBuilder()
                    .ConfigureLogging(x => x.AddSerilog())
                    .ConfigureAppConfiguration(x => x.AddJsonFile("appsettings.json"))
                    .ConfigureServices(services =>
                    {
                        services.AddThroughMessageQueue();
                        services.AddLocalDownloadCenter();
                        services.AddDownloaderAgent(x =>
                        {
                            x.UseFileLocker();
                            x.UseDefaultAdslRedialer();
                            x.UseDefaultInternetDetector();
                        });
                        services.AddStatisticsCenter(x => x.UseMemory());
                    }).Register<EntitySpider>();
                var provider = builder.Build();
                var spider = provider.Create<Spider>();
                spider.Id = Guid.NewGuid().ToString("N"); // 设置任务标识
                spider.Name = "博客园全站采集"; // 设置任务名称
                spider.Speed = 1; // 设置采集速度, 表示每秒下载多少个请求, 大于 1 时越大速度越快, 小于 1 时越小越慢, 不能为0.
                spider.Depth = 3; // 设置采集深度
                var options = provider.GetRequiredService<SpiderOptions>();
                spider.AddDataFlow(new CnblogsDataParser())
                    .AddDataFlow(new MongoEntityStorage(options.StorageConnectionString));
                spider.AddRequests("http://www.cnblogs.com/"); // 设置起始链接
                return spider.RunAsync(); // 启动
            }

            class CnblogsDataParser : DataParser
            {
                public CnblogsDataParser()
                {
                    Required = DataParserHelper.CheckIfRequiredByRegex("cnblogs\\.com");
                    FollowRequestQuerier = BuildFollowRequestQuerier(DataParserHelper.QueryFollowRequestsByXPath("."));
                }

                protected override Task<DataFlowResult> Parse(DataFlowContext context)
                {
                    context.AddData("URL", context.Response.Request.Url);
                    context.AddData("Title", context.Selectable.XPath(".//title").GetValue());
                    return Task.FromResult(DataFlowResult.Success);
                }
            }
        }
    }

**Comment by RockNHawk** [comment]
那还想请问下，爬虫支持 停机后恢复之前的进度吗？

**Comment by zlzforever** [comment]
停机恢复进度需要你自己实现一个基于数据库的 Scheduler, 可以是 Redis 也可以 RDBS, 抽空我会补上，最新重构版刚刚完成

**Comment by RockNHawk** [comment]
@zlzforever 非常感谢提供的方向指引！
