### ISSUE TITLE
当某一个请求需要上一个请求返回的数据作为参数或者 cookie 时，这个逻辑应该写在哪？

### ISSUE THREAD

**Issue by GF-Huang** [dotnetcore/DotnetSpider#164]
例如：
`POST /login` 返回一个 `Token`, 后续的请求 `POST /account/edit` 需要使用这个 `Token`，那么这两个请求就形成了前后依赖，在这个框架下怎么实现这种需求？

**Comment by zlzforever** [comment]
有很多种方式。
1. 你在爬虫的初始化时先把 token 获取得到，以后构造的 request 都带上
2. 重载 Spider 的 ConfigureRequest ， 在请发送到下载队列前更新掉这种 header 或者sign

**Comment by GF-Huang** [comment]
我只是简单举例，实际情况可能每个请求都依赖前一个请求返回的结果，这种情况是否还适合使用此框架？

**Comment by zlzforever** [comment]
你指的是下一个请求依赖上一个请求返回的某些数据才能构造正确，这种吧？也可以。就是在 DataFlow 里自己构造正确的请求，添加到队列里就行了。
框架解决几个主要的问题：
1. 并发
2. 代理
3. 解析
4. 入库
其它延伸的问题应该都可以简单的来解决，如果不能，则框架要优化。

**Comment by GF-Huang** [comment]
我看了下 NuGet 包依赖于 WebDriver，请问框架是直接用 `HttpWebRequest` 发请求还是通过 Driver 去控制某些 Headless 浏览器获取数据的？

**Comment by zlzforever** [comment]
HttpClient or Puppeter, 以后不打算官方支持 webdriver 了
