### ISSUE TITLE
Can not Duplicate GlobalValueSelector attribute as your entity example on wiki

### ISSUE THREAD

**Issue by Luudanhnhan1102** [dotnetcore/DotnetSpider#165]
![Screen Shot 2020-04-07 at 11 56 20](https://user-images.githubusercontent.com/49361410/78631560-ec355f80-78c6-11ea-9f77-74398ef850ae.png)

![Screen Shot 2020-04-07 at 11 56 49](https://user-images.githubusercontent.com/49361410/78631582-f7888b00-78c6-11ea-89fa-dc08a5398ad9.png)

**Comment by zlzforever** [comment]
https://github.com/dotnetcore/DotnetSpider/blob/master/src/DotnetSpider/DataFlow/Parser/GlobalValueSelector.cs

I already change to AllowMultiple, plz upgrade package version and try again

**Comment by Luudanhnhan1102** [comment]
![Screen Shot 2020-04-07 at 12 25 59](https://user-images.githubusercontent.com/49361410/78633169-125cfe80-78cb-11ea-8f37-d3d2ef80743f.png)
I have already updated the package to 5.0.0(beta2) and also Rebuild All on Visual Studio for Mac but it's still that error... Hmm :(

**Comment by zlzforever** [comment]
Could you please try in Rider?  or dotnet build in a terminal,  there is a testcase:

		[Fact]
		public async Task ParseEntity()

and success
