### ISSUE TITLE
It seems that Portal & Agent container is not working in Distributed Introduction in Wiki & lib folder is missing when you upload new  version of this framework

### ISSUE THREAD

**Issue by Luudanhnhan1102** [dotnetcore/DotnetSpider#167]
![Screen Shot 2020-04-08 at 18 32 57](https://user-images.githubusercontent.com/49361410/78780011-28041e00-79c8-11ea-8197-8baa15af1348.png)
![Screen Shot 2020-04-08 at 18 34 52](https://user-images.githubusercontent.com/49361410/78780023-2cc8d200-79c8-11ea-855e-58d53ad26d5b.png)
![Screen Shot 2020-04-08 at 18 36 07](https://user-images.githubusercontent.com/49361410/78780025-2d616880-79c8-11ea-9b77-955848872c57.png)

Here is the old project I have cloned. The DotnetSpider.Portal project has lib folder in wwwroot 
![Screen Shot 2020-04-08 at 18 24 59](https://user-images.githubusercontent.com/49361410/78779041-79aba900-79c6-11ea-92f9-939c5c59aac0.png)
Here is the new project and I found that it has no lib folder
![Screen Shot 2020-04-08 at 18 25 21](https://user-images.githubusercontent.com/49361410/78779470-369e0580-79c7-11ea-8e79-eff7e9d04d8c.png)

**Comment by zlzforever** [comment]
You should config a new appsettings.json and map it to your docker instance, for example:

    docker run --name dotnetspider.portal -p 7896:7896 -v /path to your config 
    folder/appsettings.json:/portal/appsettings.json dotnetspider/portal

Because the portal depens on mysql to storage data, some other configs also must be changed
