### ISSUE TITLE
我直接运行源代码的Sample，要么报错，要么没有结果？哪里出了问题？

### ISSUE THREAD

**Issue by andrew2558** [dotnetcore/DotnetSpider#169]
![无标题](https://user-images.githubusercontent.com/25080605/80051538-f1431180-854a-11ea-8151-d44a224755bb.png)
![无标题2](https://user-images.githubusercontent.com/25080605/80051604-2cdddb80-854b-11ea-9353-e69c72d5c347.png)

**Comment by zlzforever** [comment]
你代码是最新的吗，这个似乎是个已经修复的问题。在 windows 下取内存失败，我自己只有 mac 环境，win 下不好测试。你可以判断告诉我哪里出错了

**Comment by andrew2558** [comment]
我就是下载DotnetSpider-20200403.zip这个源码

**Comment by zlzforever** [comment]
...  git pull 最新的 master

**Comment by andrew2558** [comment]
谢谢
