### ISSUE TITLE
100线程就开始有408了.

### ISSUE THREAD

**Issue by ningxiaoxiao** [dotnetcore/DotnetSpider#17]
100M电信专用线,
每个请求 2.6kb

100个线程 就time out了..

Left 0 Success 6100 Error 0 Total 5973 Dowload 109 Extract 0 Pipeline 15367

**Comment by zlzforever** [comment]
1. 这么高频访问请确保对方服务器能承受(很多政府网站负载不行）
2. 确保对方没有对高频访问做限制
建议不要开这么多线程

**Comment by ningxiaoxiao** [comment]
有没有重试次数机制, time out 时间设置.  ex 中好像没有
谢谢

**Comment by zlzforever** [comment]
在Site对象里面设置CycleRetryTimes
