### ISSUE TITLE
Can not use Proxy & Kuaidaili

### ISSUE THREAD

**Issue by lolabi2202** [dotnetcore/DotnetSpider#170]
This error happened when I run your GithubSpider example at  https://github.com/dotnetcore/DotnetSpider/wiki/1-%E7%AC%AC%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84%E7%88%AC%E8%99%AB

I want to use Proxy but it doesn't work as your instruct at
https://github.com/dotnetcore/DotnetSpider/wiki/5-%E4%BD%BF%E7%94%A8%E4%BB%A3%E7%90%86

Here is the error
![Screen Shot 2020-05-08 at 17 18 54](https://user-images.githubusercontent.com/65012068/81397931-79800400-9152-11ea-80be-82a697ae86ac.png)
![Screen Shot 2020-05-08 at 17 20 54](https://user-images.githubusercontent.com/65012068/81397948-8270d580-9152-11ea-9b1c-12ccdb339d56.png)

**Comment by zlzforever** [comment]
Kuaidaili  is not a free proxy provider. So you should buy its service and get a api link to request some proxies one time. And set the api link to ProxySupplierUri in your appsettings.json

**Comment by lolabi2202** [comment]
oh I got it. Thank you so muchhhh.
