### ISSUE TITLE
All requests timeout without System.Text.Json (当没有引用System.Text.Json包时所有请求都超时的问题)

### ISSUE THREAD

**Issue by TomsonRiviera** [dotnetcore/DotnetSpider#171]
新建一个.Net Core3.1项目，复制samples中的BaseUsage.cs，然后运行，发现所有的请求都发生超时。只有引用System.Text.Json的nuget包之后才恢复正常。（您的DotnetSpider.Sample中已经引用了这个包，所以不会发生该问题）  

请问这是一个bug吗？文档和其他issue中好像均没有提到过。  

I found that if _System.Text.Json_ is not referenced when I run BaseUsage or any other samples, all the web requests will fail with a timeout. I think this problem could be a bug.
  

DotnetSpider version：5.0.1-beta2  
project target：netcoreapp3.1  

main代码   main code：
```cs
static async Task Main(string[] args)
{
	await BaseUsageSpider.RunAsync();
}
```

部分运行日志   application logs：
```
warn: DotnetSpider.Spider[0]
      7650aaec-eb8d-43fd-9287-425995529595, Cnblogs request http://www.cnblogs.com/ timeout
warn: DotnetSpider.Spider[0]
      7650aaec-eb8d-43fd-9287-425995529595, Cnblogs request http://www.cnblogs.com/ timeout
warn: DotnetSpider.Spider[0]
      7650aaec-eb8d-43fd-9287-425995529595, Cnblogs request http://www.cnblogs.com/ timeout
```

**Comment by zlzforever** [comment]
我本机测了一下不会出现你说的问题。我再找几个人测试一下

**Comment by erictuvesson** [comment]
I can confirm that I had this issue too.

I added the `System.Text.Json` NuGet Package and the requests doesn't timeout.

Thanks @Nydxy

**Comment by zlzforever** [comment]
ok, I will include this package to the DotnetSpider lib and figure out what's wrong with it
