### ISSUE TITLE
文档错误反馈

### ISSUE THREAD

**Issue by hjkl950217** [dotnetcore/DotnetSpider#173]
我在使用wiki编写demo时觉得这以下几点，希望帮助改进：
1. 现在的“第一个爬虫”的代码基于预览版，不能用在正式版上，建议在文字上再说明一下。
2. “配置式爬虫”文档中，FollowRequestSelector的属性已经修改，建议更新文档。 从`[FollowRequestSelector(XPaths = new[] {"//div[@class='pager']"})]`,变成了`[FollowRequestSelector(Expressions = new[] { "//div[@class='pager']" })]`

如果想在正式版发布后现更新文档，这个issuse可以留到记录

**Comment by zlzforever** [comment]
done

**Comment by hjkl950217** [comment]
极速响应阿
