### ISSUE TITLE
遇到小写的<!doctype html>会导致context.Selectable不正确？

### ISSUE THREAD

**Issue by paladinguo** [dotnetcore/DotnetSpider#176]
if (context.Selectable == null)
			{
				if (SelectableBuilder != null)
				{
					context.Selectable = SelectableBuilder(context);
				}
				else
				{
					var text = context.Response.ReadAsString().TrimStart();
					if (text.StartsWith("<!DOCTYPE html>") || text.StartsWith("<html>"))
					{
						context.Selectable = GetHtmlSelectable(context, text);
					}
					else
					{
						try
						{
							var token = (JObject)JsonConvert.DeserializeObject(text);
							context.Selectable = new JsonSelectable(token);
						}
						catch
						{
							context.Selectable = new TextSelectable(text);
						}
					}
				}
			}

页面请求结果：
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

提示：<!DOCTYPE> 声明对大小写不敏感。

**Comment by zlzforever** [comment]
嗯，实际用户可以自己修改 SeletableBuilder 来处理各种特殊情况。后面我做个优化

**Comment by paladinguo** [comment]
感谢！
看半天没有整明白在哪里指定自定义的SeletableBuilder ……

**Comment by zlzforever** [comment]
```
		class MyDataParser : DataParser
		{
			public MyDataParser()
			{
				AddRequiredValidator("cnblogs\\.com");
				AddFollowRequestQuerier(Selectors.XPath("."));
				
				SelectableBuilder = context =>
				{
					var bytes = context.Response.Content.Data;
					var text = bytes.ToText();
					return new HtmlSelectable(text, null, true);
				};
			}
```

**Comment by paladinguo** [comment]
搞定，多谢！
SelectableBuilder = context =>
				{
					var bytes = context.Response.Content.Data;
					var text = Encoding.Default.GetString(bytes);
					return new HtmlSelectable(text, null, true);
				};
