### ISSUE TITLE
使用AddFollowRequestQuerier方法时，当选择的元素中链接是以//开头时，请求没有被正确添加到请求队列中

### ISSUE THREAD

**Issue by null-ed** [dotnetcore/DotnetSpider#177]
![image](https://user-images.githubusercontent.com/20257310/83161435-06f3ba00-a13b-11ea-92b3-a5eef6817264.png)
按照上图所示的使用方法，当html文档如下图所示时，Request无法被正确创建，Parse方法中无法再接收到新的链接请求结果
![image](https://user-images.githubusercontent.com/20257310/83161913-9bf6b300-a13b-11ea-9349-893005727bd8.png)

**Comment by zlzforever** [comment]
若是使用了HtmlSelectable(string html, string relativeUri = null, bool removeOutboundLinks = true)，relativeUri 就是当前请求的 domain:port，会计算相对路径补齐。若是你完全自己定义，则需要你们自己补齐了。AddFollowRequestQuerier 最终会做 IsHttpScheme 验证，不合法的会过滤掉。

**Comment by RLei123** [comment]
建议将解析请求的方法暴露出来，自己解析好所有有效请求，然后调用 AddRequestsAsync 方法

**Comment by zlzforever** [comment]
AddFollowRequestQuerier 在 Parser 里改为 virtual 了，可以自己重载实现任意解析
