### ISSUE TITLE
如何获取捕抓发生错误的URL？

### ISSUE THREAD

**Issue by Tony1952466760** [dotnetcore/DotnetSpider#179]
请教个问题：如何获取发生异常的URL？
比如我向爬虫提交10个URL，如果爬取过程中有链接发生异常，如何获取时哪个链接

**Comment by zlzforever** [comment]
我在 Spider 中添加了一个新的事件

	protected event Action<Request, Response> OnError;

你可以通过注册此事件来处理错误的请求。
