### ISSUE TITLE
不满足校验的链接不需要下载

### ISSUE THREAD

**Issue by alberthe** [dotnetcore/DotnetSpider#182]
目前的逻辑是在constructor中设置了校验器，但不满足的链接照样被下载，然后再忽略。建议是否修改一下，如果校验不通过就不必下载，这样不仅节省资源，重要的是减轻被爬服务器的负担，尤其是设置了多个Parser DataFlow的情况下这个问题更加突出。

**Comment by zlzforever** [comment]
是个好建议，我思考一下如何处理

**Comment by zlzforever** [comment]
已实现
