### ISSUE TITLE
Infrastructure.SystemInformation构造器中Convert.Int64有OverflowException

### ISSUE THREAD

**Issue by tomhans2** [dotnetcore/DotnetSpider#184]
### 问题描述
在运行《第一个简单的爬虫》例子的时候，在`await builder.Build().RunAsync()`出现OverflowException，显示位置在`在 DotnetSpider.Infrastructure.SystemInformation..cctor()`，`的 System.Convert.ToInt64(UInt64 value)`。
### 配置信息
- 环境和配置：
- .Net Framework 4.8
- DotnetSpider 5.0.1.0，从Nuget下载
- Windows 10 x64 12G内存
### 检查
做了一些简单检查
1. 报错出现在Infrastucture.SystemInformation ctor 的 `TotalMemory = (int) (Convert.ToInt64(mStatus.DwTotalPhys) / 1024 / 1024);`代码中，我的机器`mStatus.DwTotalPhys`跑出来的值是18446744073709551615，跑了几次都是同一个值，而且这个值就是max_ulong。
2. 看过`GlobalMemoryStatus`的文档，用法应该没有问题，上面说用大于4G的用`GlobalMemoryStatusEx`，这个我不太确定，用`GlobalMemoryStatusEx`测试了后发现内存返回的数值都是0
3. 调整了`MemoryStatus`结构体：
目前使用ulong的情况下，`DwTotalPhys和DwAvailPhys`都是18446744073709551615，且`DwAvailPageFile，DwTotalVirtual，DwAvailVirtual`都是0。将ulong换成uint，内存变量基本上都是4294967295，只有`DwAvailVirtual`少一点4167479296

**Comment by tianweichong** [comment]
你好，处理办法能够写的更清楚些吗，现在我也出现这个问题，不知道怎么处理

**Comment by zlzforever** [comment]
单机应用不再尝试读取内存信息了，应该不会再报错了。可以更新一下代码
