### ISSUE TITLE
异步启动多个Spider，第一个Spider的Task状态始终为Running

### ISSUE THREAD

**Issue by wu-wenzhi** [dotnetcore/DotnetSpider#19]
Spider启用：
`            foreach (DotnetSpider.Core.Spider s in SpiderList)
            {
                s.OnClosed += s_OnClosed;
                SpiderTaskList.Add(s.RunAsync());
            }`
在s_OnClosed中循环处理SpiderTaskList[i].Status中的状态，第一个Task始终为Running

**Comment by zlzforever** [comment]
可否发一个代码呢方便我重现问题？zlzforever@163.com.  我刚在DotnetSpider.Sample的Program的MyTest里测试了一下没有你说的问题。

**Comment by wu-wenzhi** [comment]
已经把测试代码发到您邮件了，请查收
