### ISSUE TITLE
请教：如何同时运行多个爬虫，并且每个爬虫使用各自的配置呢？

### ISSUE THREAD

**Issue by fmpfmp** [dotnetcore/DotnetSpider#191]
请教：如何同时运行多个爬虫，并且每个爬虫使用各自的配置呢？

**Comment by zlzforever** [comment]
已进群讯问并解决

**Comment by chinasqzl** [comment]
@zlzforever  群不加新人了，答案为什么不贴一下呢？

**Comment by zlzforever** [comment]
var spider1= builder1.Build().RunAsync(); var spider2=builder2.Build().RunAsync(); Task.WaitAll(spider1,spider2);
