### ISSUE TITLE
Can not use proxy

### ISSUE THREAD

**Issue by bebestmaple** [dotnetcore/DotnetSpider#197]
I have a proxy supplier named FreeProxySupplier,it create a httpclient use below code like sample:
`_httpClientFactory.CreateClient("DotnetSpider_Proxy_Supplier_freeProxy")`
and use it in spider
`builder.UseProxy<FreeProxySupplier>();`
but i throw an exception,
i just found that `UseProxy<T>()` in `DotnetSpider.Proxy.ServiceCollectionExtensions`  would use `ProxyHttpMessageHandlerBuilder` .also use it when create httpclient in supplier ,
` if (!Name.StartsWith(Const.ProxyPrefix))
                    {
                        throw new SpiderException(
                            "You are using proxy http client builder, but looks like your http client name is incorrect");
                    }

                    var uri = Name.Replace(Const.ProxyPrefix, string.Empty);
                    var handler = new ProxyHttpClientHandler
                    {
                        UseCookies = true,
                        UseProxy = true,
                        ProxyService = _proxyService,
                        AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate,
                        Proxy = new WebProxy(uri)
                    };

                    DefaultHttpMessageHandlerBuilder.SetServerCertificateCustomValidationCallback(Services, handler);
                    PrimaryHandler = handler;`
Also,in file  `DotnetSpider\Proxy\DefaultProxyValidator.cs` function `IsAvailable(Uri proxy)` code: `var httpClient = _httpClientFactory.CreateClient($"PROXY_{proxy}");`
how can i know to create so many httpclients named with proxy url,and it also would throw exception ,because it use ProxyHttpMessageHandlerBuilder

**Comment by zlzforever** [comment]
I fixed proxy issues.
1. Start up a Fiddler and config it allow remote proxy
2. Update the DotnetSpider.Sample/samples/ProxySpider.cs: x.ProxyTestUrl = "http://192.168.31.200:8866";  to your ip:port.
3. Run the proxy sample spider: await ProxySpider.RunAsync();
