### ISSUE TITLE
请求出现超时后，此代码将导致连续的请求超时和队列堵塞。应该添加 if (_dict.ContainsKey(hash)) 判断

### ISSUE THREAD

**Issue by Axlingking** [dotnetcore/DotnetSpider#198]
https://github.com/dotnetcore/DotnetSpider/blob/c5124711aaacb01ede0dcb9a8ea1fd18dbcf4c3e/src/DotnetSpider/Infrastructure/RequestedQueue.cs#L51

**Comment by zlzforever** [comment]
下一版本代码修复并添加测试用例
