### ISSUE TITLE
第一个简单的爬虫错误

### ISSUE THREAD

**Issue by JiangYueLin7** [dotnetcore/DotnetSpider#199]
https://github.com/dotnetcore/DotnetSpider/wiki/1-%E7%AC%AC%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84%E7%88%AC%E8%99%AB

The type initializer for 'DotnetSpider.Infrastructure.SystemInformation' threw an exception.

![image](https://user-images.githubusercontent.com/25028649/108340563-ad28a800-7213-11eb-836f-6328c284d3c4.png)

**Comment by JiangYueLin7** [comment]
我跟着例子走的

**Comment by zlzforever** [comment]
用的是哪个版本的包。可否帮我定位一下是哪一行代码？这是因为取不同操作系统的系统参数（内存）出错了

**Comment by JiangYueLin7** [comment]
> 用的是哪个版本的包。可否帮我定位一下是哪一行代码？这是因为取不同操作系统的系统参数（内存）出错了

用的是5.0.0-beta1版本,代码是Main方法下的 await builder.Build().RunAsync();
