### ISSUE TITLE
是否可以获取ajax加载后的网页

### ISSUE THREAD

**Issue by the404** [dotnetcore/DotnetSpider#20]
网页是在ajax结束之后，才有了内容数据，而我又需要在ajax渲染完成之后爬取，请问是否支持，如果支持的话具体应该怎么配置呢？

**Comment by zlzforever** [comment]
异步加载的数据有2总方法
1. 第一优先您应该先去分析一下网站的异步请求API, 直接构造请求采集数据(框架支持JsonPath)
2. 第二如果API有加密等导致您无法模拟出正确的请求, 可以把Downloader设置为WebDriverDownloader
