### ISSUE TITLE
如何实现登录？

### ISSUE THREAD

**Issue by ysqopen** [dotnetcore/DotnetSpider#200]
请问怎么登录？
我好象没看到有这个例子。

**Comment by zlzforever** [comment]
登录是需要自己了解现有的几种鉴权方式。

COOKIE:

1. 这种登录你自己写一个 httprequest，可能要搞定各种验证码，获取到 Cookie 设置到各个请求上即可
2. 若是 cookie 生效时间长，也可以手动复制设置到各个请求上
3. 也可以自己单开一个线程、进程获取 cookie 爬虫在检测到 cookie 失效后获取新的 cookie

JWT

同 Cookie 要自己走一套流程获取到 Token 设置到对应 Header 上
