### ISSUE TITLE
数据和对应的html都是后加载如何爬取 

### ISSUE THREAD

**Issue by JYY20210419** [dotnetcore/DotnetSpider#205]
vue框架
index.html的body里放了一个<div id=app></div>            
然后通过某个js 拿到后台数据以后把【内容A的html】填进<div id=app></div>

我如果直接请求这个index，没法拿到【内容A的html】
那我要怎么爬取【内容A的html】的元素

**Comment by zlzforever** [comment]
js 发生了另外一个请求，这是需要 js engine 才能执行并渲染的。你可以选择使用如 webdriver 或者自己分析 js 请求，构造请求来获取数据
