### ISSUE TITLE
列表页面和详情页面分成两个DataFlow 

### ISSUE THREAD

**Issue by Chfei1** [dotnetcore/DotnetSpider#206]
循环完所有列表页面才会执行到详情页面。怎么写才可以抓取完当前分页列表 继续抓取当前分页下的详情，然后再继续下一页。

**Comment by songyunhmiLY** [comment]
我是做成2个spider，处理列表内容的时候再spider.run，不知道是否合理

**Comment by zlzforever** [comment]
Scheduler 可以配置深度优先，广度优先

**Comment by Chfei1** [comment]
> Scheduler 可以配置深度优先，广度优先

Ok 谢谢
