### ISSUE TITLE
能否发Release

### ISSUE THREAD

**Issue by Abel-Liu** [dotnetcore/DotnetSpider#21]
能否发布Nuget的时候发release，可以看到不同版本的代码。现在想找某个Nuget版本的源码不太容易。

**Comment by zlzforever** [comment]
等我研究一下怎么能简单实现。

**Comment by Abel-Liu** [comment]
GitHub的Release功能很方便，您可以在项目设置中开放。
发布新的NuGet版本时，在项目中新建一个Release，填写对应的NuGet版本。每个Release都会自动附带当前的源码，这样可以下载不同版本的源码进行调试。

**Comment by zlzforever** [comment]
学到了。已经好了，感谢
