### ISSUE TITLE
无法从起始页生成新的地址

### ISSUE THREAD

**Issue by ningxiaoxiao** [dotnetcore/DotnetSpider#22]
如果没有从页面得到ResultItem,
AddTargetRequest 增加的页面没有作用? 这是个bug嘛? 

一个页面不一定会有结果,但会生成新的地址阿

**Comment by zlzforever** [comment]
Spider.SkipWhenResultIsEmpty默认值是true, 即如果结果为空，则忽略所有targetUrl
