### ISSUE TITLE
[feature] 框架是否能自动生成Host request header

### ISSUE THREAD

**Issue by a157147899** [dotnetcore/DotnetSpider#221]

**Comment by a157147899** [comment]
如题，在未手动设置的情况下，框架是否能自动生成Host request header？从而避免400 Bad Request响应。

原因是在请求下面的URL时，发现无论怎么设置Host header都返回400，但是用postman却可以成功请求并响应，查看postman的Host header显示是自动生成的，且不能修改。

https://arcteryx.com.au/collections/past-seasons

![image](https://user-images.githubusercontent.com/1812136/142391827-1b7aff2b-f6b4-494b-8e7d-bd39adebf6b4.png)

**Comment by zlzforever** [comment]
Header 是可以你自己设置的。框架层面最好保持最原始状态，你这个例子可能要加上，但是如果别人加上就出问题呢？

**Comment by zlzforever** [comment]
Header 是可以你自己设置的。框架层面最好保持最原始状态，你这个例子可能要加上，但是如果别人加上就出问题呢？
