### ISSUE TITLE
怎样在DotnetSpider中使用PuppeteerSharp？

### ISSUE THREAD

**Issue by ling0x** [dotnetcore/DotnetSpider#222]
就像Scrapy和Splash一样，能不能提供一个在DotnetSpider框架中结合使用PuppeteerSharp来填写表格、自动化browser、访问Javascript网站的example?

**Comment by zlzforever** [comment]
现在是完全通过消息来通信。对下载端的自定义没有想过要怎么操作、实现会好一点
