### ISSUE TITLE
怎么使用sqlserver数据库呢   

### ISSUE THREAD

**Issue by gongzhx1998** [dotnetcore/DotnetSpider#224]
不是很明白

**Comment by zlzforever** [comment]
SqlServerEntityStorage

**Comment by ghost** [comment]
> SqlServerEntityStorage

你好，能说的详细点吗

**Comment by zlzforever** [comment]
你看一下 Sample 项目，搜索 AddDataFlow。

AddDataFlow(new SqlServerEntityStorage());
