### ISSUE TITLE
重试的request请求它的Properties和headers被清理掉了，请问怎么解决

### ISSUE THREAD

**Issue by ethanpeng8** [dotnetcore/DotnetSpider#231]
**我碰到了一个request再重试第2次或第三次的时候，它的Properties和Headers都为空，被清理掉了。是不是下面两段代码的执行顺序变了影响的？清理context的代码先执行所以导致Properties和Headers被清空了**
![image](https://user-images.githubusercontent.com/64203190/174426968-fdb33bf5-e9cb-40f5-8a1f-d92e2b152032.png)
![image](https://user-images.githubusercontent.com/64203190/174427185-84703017-3975-48c2-8d87-8b60a236838d.png)

**Comment by ethanpeng8** [comment]
**是否可以向这里添加request的副本？**
![image](https://user-images.githubusercontent.com/64203190/174428398-0c2a20a2-dc27-4095-bcc3-a799a4a769e8.png)

**Comment by zlzforever** [comment]
应该可以，如果你测试没问题的话我这么改一下

**Comment by zlzforever** [comment]
我测试了一下没有复现，需要更多信息
