### ISSUE TITLE
XPathSelector内存消耗过大

### ISSUE THREAD

**Issue by ethanpeng8** [dotnetcore/DotnetSpider#235]
以前的.net framework版本好像不存在这个问题，现在的XPathSelector需要去频繁的创建HtmlDocument导致内存消耗有点大

**Comment by ethanpeng8** [comment]
动不动就1G以上

**Comment by lexa044** [comment]
Hi, I would like to help here. However I do not speak Chinese, could you please explain what the issue is in English?

**Comment by TheRealKraytonian** [comment]
use chatgpt to understand them you have so many translation tools to use

Rough Translation
The text you provided in Chinese translates to English as:

"XPathSelector High Memory Consumption #235

It seems that this issue did not exist in previous .net framework versions. The current XPathSelector requires frequent creation of HtmlDocument, leading to a bit high memory consumption. It easily exceeds 1G."

This appears to be a comment or a bug report related to the memory consumption of XPathSelector in a certain version of the .NET framework, contrasting it with previous versions.
