### ISSUE TITLE
用Host形式启动后，执行所有任务后仍在运行， 请问完成后怎么关闭

### ISSUE THREAD

**Issue by ado5** [dotnetcore/DotnetSpider#246]
public static async Task RunAsync()
		{
			var builder = Builder.CreateDefaultBuilder<CnblogsSpider>();
			builder.UseSerilog();
			builder.UseDownloader<HttpClientDownloader>();
			builder.UseQueueDistinctBfsScheduler<HashSetDuplicateRemover>();

			await builder.Build().RunAsync();
		}

我添加了10个请求， 10个请求执行完毕后， 控制台显示仍在运动， success:10, left:0, 请问这种怎么设置全部执行完毕后停止，触发全部执行完成的方法？

**Comment by zlzforever** [comment]
EmptySpleepTime, 默认超过一定时间 30 秒没有新的链接任务是会退出的

**Comment by ado5** [comment]
> EmptySpleepTime, 默认超过一定时间 30 秒没有新的链接任务是会退出的

我发现一个问题， 如果链接出现了 Request Error， 然后多次自动重试请求的时候， RequestedTimes 增加多次， 但结果都是请求错误,

SchedulerBase.cs

		public async Task<int> EnqueueAsync(IEnumerable<Request> requests)
		{
			var count = 0;
			foreach (var request in requests)
			{
				_requestHasher.ComputeHash(request);    <--  如果错误请求重试的的， 计算Hash值是一样的
				if (await DuplicateRemover.IsDuplicateAsync(request))
				{
					continue;   <-- Hash值是一样直接Continue了。 链接以后再也没有执行
				}

				await PushWhenNoDuplicate(request);
				count++;
			}

			return count;
		}

**Comment by zlzforever** [comment]
错误请求重试是指哪里生成的请求？

**Comment by zlzforever** [comment]
已修复，可以查看源码和使用最新 nuget 包
