### ISSUE TITLE
Where can I find documentations?

### ISSUE THREAD

**Issue by Sojaner** [dotnetcore/DotnetSpider#248]
Hi!

Thanks for the efforts and advance codebase.

I was wondering if there is any documentation that I can look at and get familiar with the way the code works.

I have seen the [wiki](https://github.com/dotnetcore/DotnetSpider/wiki) and have looked at the sample projects. But I'm looking for something that explain the different classes and methods.

For example, for finding the difference between `UseQueueDfsScheduler`, `UseQueueBfsScheduler`, and `UseQueueDistinctBfsScheduler` I had to read the source code and retrieve the comments in the code and use a translator to understand the comment.

Is there an online documentation or any easier way to understand the code?

Thanks again. :)

**Comment by zlzforever** [comment]
UseQueueDfsScheduler: deep first search
UseQueueDistinctDfsScheduler: deep first search, ignore same url
UseQueueBfsScheduler: Breath First Search
UseQueueDistinctBfsScheduler: Breath First Search, ignore same url

**Comment by Sojaner** [comment]
Thank you for the response.

I have another question.

HtmlSelectable uses HtmlNode internally and I need to access the attributes on the HtmlNode, but the nodes object is not exposed. Do you have a way of accessing the HtmlNode object outside of the HtmlSelectable instance?
