### ISSUE TITLE
English documentations

### ISSUE THREAD

**Issue by Sojaner** [dotnetcore/DotnetSpider#250]
I have translated the code base's documentation, comments, and strings into English.

I have also fixed some vulnerability issues and fixed the failing unit tests. ~~I will soon create a pull request with these fixes. 🙂~~ 

~~The code is here: https://github.com/Sojaner/DotnetSpider/tree/en-updated what do you think, should I create a new library version in English, or what do you think?~~ The translations are on the `master` branch of my fork at https://github.com/Sojaner/DotnetSpider and I will later on create the English version of the NuGet package.

**Also**, I have developed a dotnet tool that can translate the whole code base at once. It's called [transooner](https://www.nuget.org/packages/transooner/) for anyone who ends up here and is interested.

**Comment by Sojaner** [comment]
#251 is the PR for the fixes and updates (excluding the English translations)

**Comment by zlzforever** [comment]
Welcome your PR~  Thanks
