### ISSUE TITLE
bug:‘xxxEntity’ does not contain a definition for 'GetTableMetadata'

### ISSUE THREAD

**Issue by shelley-xl** [dotnetcore/DotnetSpider#254]
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException:“'DotnetSpider.Sample.samples.EntitySpider.CnblogsEntry' does not contain a definition for 'GetTableMetadata'”

src\DotnetSpider\DataFlow\Storage\Entity\RDEntityStorageBase.cs 中: 第 120 行

**Comment by shelley-xl** [comment]
\src\DotnetSpider\DataFlow\Storage\Entity\EntityBase.cs 中: 第 22 行

原代码：
TableMetadata IEntity.GetTableMetadata()
{
    ...
}

修改为：
public TableMetadata GetTableMetadata()
{
    ...
}

即可解决问题

因为缺少访问修饰符，私有的，外部无法访问

**Comment by zlzforever** [comment]
已修复，发布了新的 nuget 包
