### ISSUE TITLE
Unable to launch DotnetSpider.Agent program

### ISSUE THREAD

**Issue by jasonzhouau** [dotnetcore/DotnetSpider#256]
It will throw exception
```
System.ArgumentException: Cannot instantiate implementation type 'DotnetSpider.Downloader.IDownloader' for service type 'DotnetSpider.Downloader.IDownloader'.
```
HttpClientDownloader already added to in services.AddAgentHostService()
https://github.com/dotnetcore/DotnetSpider/blob/a2939999426378d1576cc26ad4e8277c43721ef5/src/DotnetSpider.Agent/Program.cs#L39

Why need to add it again here
https://github.com/dotnetcore/DotnetSpider/blob/a2939999426378d1576cc26ad4e8277c43721ef5/src/DotnetSpider.Agent/Program.cs#L38

Thank you

**Comment by zlzforever** [comment]
Pushed, pls have a try

**Comment by jasonzhouau** [comment]
Confirmed. Fixed. Thanks
