### ISSUE TITLE
【问题】spider 中怎么使用http代理

### ISSUE THREAD

**Issue by hurui79** [dotnetcore/DotnetSpider#257]
能给个例子么。。。。或者在哪找例子也行
看了这个https://github.com/dotnetcore/DotnetSpider/issues/96  也没看到例子，还是没懂应该怎么用

**Comment by zlzforever** [comment]
1. 参考项目中  ProxySpider 示例，核心在： 
```
            builder.UseProxy<FiddlerProxySupplier, DefaultProxyValidator>(x =>
            {
                x.ProxyTestUrl = "http://localhost:8866";
            });

```
2. FiddlerProxySupplier 提供一个代理池，返回的是 List<URI> 比如你的代理地址 http://x.x.x.x:8083，爬虫会有定时任务 ProxyBackgroundService 去获取代理地址，加到代理池中
3. DefaultProxyValidator 是指测试代理是否可用的地址
4. 注入了 HttpMessageHandlerBuilder -> ProxyHttpMessageHandlerBuilder，其会根据代理信息创建相应的 handler
