### ISSUE TITLE
Typo in file name "SpiderExceptoin.cs"

### ISSUE THREAD

**Issue by MungoWang** [dotnetcore/DotnetSpider#26]
Path: src/DotnetSpider.Core/SpiderExceptoin.cs
Should be "SpiderException.cs"

**Comment by MikeCheers** [comment]
thats right




| |
张晓亭
|
|
邮箱：mikecheers@126.com
|

签名由 网易邮箱大师 定制

On 12/09/2017 22:00, MungoWang wrote:

Path: src/DotnetSpider.Core/SpiderExceptoin.cs
Should be "SpiderException.cs"

**Comment by zlzforever** [comment]
@MungoWang @MikeCheers Thanks

**Comment by MungoWang** [comment]
Issue fixed, hence closing it.
