### ISSUE TITLE
能不能添加一个 类似 Web那边的Ajax的轻量级请求,最好是当前的DataParser 就返回结果的那种.

### ISSUE THREAD

**Issue by sgf** [dotnetcore/DotnetSpider#262]
目前每个子链接(哪怕是Ajax调用) 都要搞一个 新的DataParser ,然后用 AddFollowRequests链接下一个DataParser  这就挺麻烦的.

另外,Url解析有没有现成的?为此我还安装了asp.netcore 的相关dll来解析url的Query,感觉相当麻烦.

ISelector 只有value没有 标签属性.也无法获取Display文本,也无法区分RawHtml.....

选择器多搞几个比如 GetListCSS  GetListXPath GetListJSPath 之类的 目前的SelectList用起来并不方便.Select方法同理.

**Comment by zlzforever** [comment]
1. 框架的核心是抽象出几个关键的东西进行实现、避免重复。如：请求、存储、多线程
2. DataParser 并不强制要求 1:1，相象一下，如果没有框架，你会怎么写爬虫。DataParser 有一个方法、正则去判断是否应该进去这个解析器。但是如果全部集中在一起，则多了如：if(url is xxxx) else if(url is yyyy) 这种低码。是多写类合式、还是 if else 合适没有统一说法。
3. 存储器同理
4. XPathSelector 可以查询属性，不同的返回结果要用不同的查询器。JsonPathSelector

**Comment by sgf** [comment]
> 1. 框架的核心是抽象出几个关键的东西进行实现、避免重复。如：请求、存储、多线程
> 2. DataParser 并不强制要求 1:1，相象一下，如果没有框架，你会怎么写爬虫。DataParser 有一个方法、正则去判断是否应该进去这个解析器。但是如果全部集中在一起，则多了如：if(url is xxxx) else if(url is yyyy) 这种低码。是多写类合式、还是 if else 合适没有统一说法。
> 3. 存储器同理
> 4. XPathSelector 可以查询属性，不同的返回结果要用不同的查询器。JsonPathSelector

类太重。if else 简单。如果是需要判断是否要进入一个链接的话，其实可以放一个Where也就是Lamabda作为过滤器。
JsonPathSelector 虽然可以查询属性，但是其语法并不是很友好。不如CSS选择器。

目前我已经选择了 AngleSharp。
原因如下：
1.我只是临时起意，并不需要过于重量级，也不需要写这么多类，主要是我懒，作为程序员理论上来说多敲一个字符都是多余的。
2.相对来说足够简单，并且以上我提到的AngleSharp基本都支持。只是AngleSharp不成熟(尤其是JS模块)，我遇到了两个bug。

当然作为基础框架来说，我觉得DotnetSpider确实不错，仁者见仁智者见智，因此我尊重作者的选择。

PS：虽然正则不错，但是我不熟悉，即使是平时，我也是宁愿写Lambda，多谢string的扩展方法，也不愿意去写正则。
正则并不友好。虽然有5分钟，15分钟，30分钟入门之类的玩意儿。但是本质上我对这玩意儿是抵触的。哪怕我是一个十年的老菜鸟，至今依然觉得如此。
