### ISSUE TITLE
定时爬虫，同一个地址每5分钟爬取一次，实现增量爬取，怎么实现

### ISSUE THREAD

**Issue by dflstone** [dotnetcore/DotnetSpider#265]

**Comment by zkchen** [comment]
来信已收到。

**Comment by dflstone** [comment]
就像例程里面的地址：https://news.cnblogs.com/n/page/1，如何每5分钟，把这个地址爬取一次
1、单开线程？spider里面AddRequestsAsync？
2、系统定时执行 爬虫程序？
3、请指教

**Comment by zlzforever** [comment]
这个确实要自己管控。比如定时往请求队列中增加链接
