### ISSUE TITLE
Could please add some comments

### ISSUE THREAD

**Issue by mrtylerzhou** [dotnetcore/DotnetSpider#29]
Could you please add some comments on classes,methods and properties so that when  use visual studio i can hover on them to see the comments and get a rough idear about what it is used for

**Comment by yang-xiaodong** [comment]
@zlzforever Do we have a plan to add comments？ I think we can raise the priority of this work.

**Comment by mrtylerzhou** [comment]
yes I can,But the problem is that it is the first time i begin to use dotnetSpider,and do not have any experiences in this field.The most important thing is that the codes are not written by me,so if i try to add comments by my understanding may cause issues.The most ideal plan is that if you already have chinese comments,I can spare some hours a day to translate it into English.we can talk about the plan in detail,even though this project do not have origional comments.

**Comment by mrtylerzhou** [comment]
If you have origional chinese version of comments,I can help to translate them into English ones.So that you can focus on coding.

**Comment by alexinea** [comment]
As title said, we need comments more than code as well 👦 :)

**Comment by zlzforever** [comment]
@mrtylerzhou  Sure, will add Chinese comments firstly, maybe someone can help me translate it to English.

**Comment by mrtylerzhou** [comment]
@zlzforever I can help to translate the comments to English,and If you have plans to build a document site.I can also help to translate long documents.We can talk about the plan in detail.I major in English literature and past the tem8 many years ago.Now I'm a dotnet developers and have read severals origional english books about technology these years.I think I'm capable of this work and the most important thing is that I think Chinese projects should be known by the world.I saw serval japaness even south american projects documented in english.But most chinese projects only or mainly in Chinese.

**Comment by moonheart** [comment]
I think we need document for this project, both Chinese and English.

**Comment by mrtylerzhou** [comment]
@moonheart  Agree with you.It is perfect if it can behaves like dotnet library:if the environment is english,it show english.If the environment is chinese,it will show chinese.

**Comment by zlzforever** [comment]
@mrtylerzhou @moonheart will start soon, thanks you guys support.

**Comment by zlzforever** [comment]
已经开始

**Comment by robyle** [comment]
Chinese Document & English Document both pubulish.

**Comment by alexinea** [comment]
@robyle Nice Boat

**Comment by zlzforever** [comment]
guys, I wrote Chinese comments already. My next plan is to write usage document/guide. Hope someone help to translate those comments

**Comment by moonheart** [comment]
I'm working on translations for namespace `DotnetSpider.Core.Downloader` currently, with following comment format which is posted [here:](https://stackoverflow.com/a/6267658)
```csharp
    /// <summary>
    /// Here is English Comments
    /// </summary>
    /// <summary xml:lang="zh-CN">
    /// 这里是中文注释
    /// </summary>
    public class ReplaceHandler : AfterDownloadCompleteHandler{}

```

**Comment by ray-yuruisoft** [comment]
is there a link to the Documents site?@robyle @zlzforever

**Comment by yang-xiaodong** [comment]
@ray-yuruisoft 
More detailed documentation is still in progress, you can always follow the [wiki](https://github.com/dotnetcore/DotnetSpider/wiki) to understand recent progress.
