### ISSUE TITLE
MySqlEntityPipeline在InsertNewAndUpdateOld模式插入数据时，生成的SQL语句报语法错误

### ISSUE THREAD

**Issue by zrczrc** [dotnetcore/DotnetSpider#31]
MySqlEntityPipeline/GenerateInsertNewAndUpdateOldSql()
`var sql =`
`$"INSERT INTO `{adapter.Table.Database}`.`{tableName}` ({cols}) {colsParams} ON DUPLICATE KEY UPDATE {setParams};";`
改成
`var sql =`
`$"INSERT INTO `{adapter.Table.Database}`.`{tableName}` ({cols}) VALUES ({colsParams}) ON DUPLICATE KEY UPDATE {setParams};";`
就没问题了。

**Comment by zlzforever** [comment]
已解决
