### ISSUE TITLE
 More details about installation.

### ISSUE THREAD

**Issue by iny** [dotnetcore/DotnetSpider#32]

**Comment by zlzforever** [comment]
I am working on re-struct and add comments now. After finish all comments will write more documents.

**Comment by iny** [comment]
When is it going to end? @zlzforever  Would you e-mail me? [ilkiny21@gmail.com](mailto:ilkiny21@gmail.com)

**Comment by zlzforever** [comment]
Will do :)

**Comment by iny** [comment]
I'm waiting for a response 👍 @zlzforever

**Comment by iny** [comment]
How can I access this screen? I get an error when I run DotnetSpider.Core @zlzforever 

<img src="https://raw.githubusercontent.com/dotnetcore/DotnetSpider/master/images/1.png">

**Comment by zlzforever** [comment]
It's another project: https://github.com/zlzforever/DotnetSpider.Enterprise, and depeneds CI/CD to use it. Will document how to use it next step.

**Comment by iny** [comment]
I am getting like this error. @zlzforever 
![123](https://user-images.githubusercontent.com/24559998/34601956-0754e1f0-f20f-11e7-84fb-0905683b70ff.png)

**Comment by zlzforever** [comment]
Because your didn't start the Web project.

**Comment by iny** [comment]
Well, I got that problem. Now the following image says there is a connection error.
![123](https://user-images.githubusercontent.com/24559998/34606280-d89bd448-f21f-11e7-8194-847ded5fabb7.png)
Do I have to enter the MySqlConnection tab on appsettings.Development.json?

Will I add automatic queries when I enter the information? @zlzforever

**Comment by zlzforever** [comment]
No, I used EF in the Enterprise project , so firstly you should update the SqlServer connect string and then run command: update-database in the NUGET manage console to create database and table.
The best way to use Enterprise project is waiting my documents....

**Comment by iny** [comment]
When will the documents be refreshed? Is there a date? @zlzforever
