### ISSUE TITLE
支持”断点续传“吗？ 如果程序中途由于意外断掉，重启 spider 现在有处理机制么？ 

### ISSUE THREAD

**Issue by xiaoyc** [dotnetcore/DotnetSpider#40]
Will the spider automatically skip the urls  which has beed downloaded?

**Comment by zlzforever** [comment]
如果使用的是RedisScheduler是可以的。内存型的Queue是不行的。可以实现一个数据库型的、文件型的Queue调度, 你可以尝试实现一个。

**Comment by xiaoyc** [comment]
非常感谢。
