### ISSUE TITLE
there is a bug of HttpClientDownloader 

### ISSUE THREAD

**Issue by jeraytang** [dotnetcore/DotnetSpider#48]
the  DowloadContent method of   HttpClientDownloader
code:
_// TODO: 代理模式下: request.DownloaderGroup 再考虑
					var proxy = spider.Site.HttpProxyPool.GetProxy();
					request.Proxy = proxy;
					httpClientItem = HttpClientPool.GetHttpClient(spider, this, CookieContainer, proxy?.GetHashCode(), CookieInjector);
					httpClientItem.Handler.Proxy = httpClientItem.Handler.Proxy ?? proxy;_

there is a issue  at this line **"httpClientItem.Handler.Proxy=httpClientItem.Handler.Proxy ?? proxy;"**

if you  reuse httpClient instance, the httpClientItem.Handler.Proxy can not  modify the Proxy. 
it will thow exceotion :**This instance has already started one or more requests. Properties can only be modified before sending the first request.**

**Comment by zlzforever** [comment]
I will fix it this week, thanks for your report.
