### ISSUE TITLE
How to support multiple starturls and multiple page processors

### ISSUE THREAD

**Issue by bruceliu2008** [dotnetcore/DotnetSpider#53]
Hi,
    For example,
www.aaa.com and www.bbb.com, they require different page processor, processorX and processorY.
I only see AddStartUrls() method, but how to assign different page processor for each start url?

Thanks,

**Comment by zlzforever** [comment]
There is a ITargetUrlsExtractor property in BasePageProcessor, and I implement a RegionAndPatternTargetUrlsExtractor to switch different processor.  Please have a look at the sample in file:

DotnetSpider.Sample.Cnblogs

there are two processors: BlogSumaryProcessor and NewsProcessor

**Comment by bruceliu2008** [comment]
Thanks.
It works.
But I still have to call site.AddStartUrl() twice.

**Comment by zlzforever** [comment]
Use site.AddStartUrls

**Comment by bruceliu2008** [comment]
thanks for the help.
