### ISSUE TITLE
关于使用代理报：此实例已经启动一个或多个请求。只能在发送第一个请求之前修改属性

### ISSUE THREAD

**Issue by gdutzhulm** [dotnetcore/DotnetSpider#55]
使用代理采集下一个链接的时候会报：“此实例已经启动一个或多个请求。只能在发送第一个请求之前修改属性”，我看代理类是实现了IDisposable接口的，是不是因为没释放资源的缘故？在哪里释放呢？我的代理类如下：
```
public class HttpProxyPool : IHttpProxyPool
    {
        public void Dispose()
        {           
        }

        public UseSpecifiedUriWebProxy GetProxy()
        {
            var uri = new Uri("http://125.126.162.105:45504");
            return new UseSpecifiedUriWebProxy(uri);           
        }
        public void ReturnProxy(UseSpecifiedUriWebProxy proxy, HttpStatusCode statusCode)
        {            
        }
    }
```

设置代理代码：
`site.HttpProxyPool = new HttpProxyPool();`

**Comment by xljiulang** [comment]
一个HttpClientHandler实例，只能设置最多一次代理。如果想变更代理，只要创建一个新的HttpClientHandler实例，并把旧的实例的相关属性复制过来。

**Comment by zlzforever** [comment]
@gdutzhulm 出错原因是如 @xljiulang 所说，在产生了实际请求之后, TCP连接已经建立, 端口的映射已经完成, 端口释放不是C#代码一个dispose能解决的。请问你使用的代码版本是？HttpProxyPool会对端口等做hash分组，如果切换代理，会重新实例httpclienthandler.

**Comment by gdutzhulm** [comment]
我用的版本是2.4.4 @zlzforever

**Comment by zlzforever** [comment]
请在nuget管理器中使用DotnetSpider.Core 最新版， DotnetDpider2.Core是之前ID被别人占用使用的名字

**Comment by gdutzhulm** [comment]
感谢！确实使用 DotnetSpider.Core 最新版就没这问题了。 @zlzforever
