### ISSUE TITLE
第一个简单的爬虫 的例子报错

### ISSUE THREAD

**Issue by yuchen1030** [dotnetcore/DotnetSpider#59]
1、例子报错  https://github.com/dotnetcore/DotnetSpider/wiki/1.-第一个简单的爬虫     报错：Download https://github.com/zlzforever failed:发生一个或多个错误。
环境：net45，DotnetSpider2.Core.2.4.4 .
2、如何爬 带搜索参数的页面？    例如这个页面 http://list.youku.com/category/show/c_96_s_1_d_1_p_{i}.html 中 ，搜索框分别是  "后来的我们",  "少林足球","羞羞的铁拳"，如何优雅地爬到这3个页面呢？
3、这个组件，会自动切换ip爬么？要怎么切换ip呢？

**Comment by zlzforever** [comment]
1. 这是github访问不稳定的原因，已经测试无问题，但页面更新导致抽取数据为空
2. 有多种方式：a. 知道有多少页自己构造加到StartUrls a. 使用targetextractor筛选符合规则的目标链接 c. 使用AutoIncrementTargetUrlsExtractor
3. 切换IP需要你有ADSL拨号环境 或者使用代理池，框架都支持。

**Comment by kasnti** [comment]
作者你好，我也是wiki中第一个例子《第一个简单的爬虫》报错：“DotnetSpider.Core.Env”的类型初始值设定项引发异常。序列不包含任何匹配元素。
环境：.net4.5,DotnetSpider2.Core.2.4.4
这是什么原因呢？并且下载别人博客上写好的源码运行也是报这个错误，怀疑本地环境有问题。

**Comment by zlzforever** [comment]
请使用DotnetSpider.Core的包了，因为一个不可控原因当时只能使用DotnetSpider2这个包名，后面的更新都在DotnetSpider.Core里了，你的版本太老我不太好找错误

**Comment by newlifes01** [comment]
在3.0版以经无法运行了吗
