### ISSUE TITLE
最佳实践

### ISSUE THREAD

**Issue by hippieZhou** [dotnetcore/DotnetSpider#60]
你好，我想请教你一下关于使用 DotnetSpider Framework 的最佳实践：

> 场景：我需要从一个网站的首页中拿到所有种类的一级链接，然后再通过抓起到的一级链接组装成一个新的二级链接，我需要将所有的二级链接执行抓起数据。
        
> 问题：我创建了一个 Spider，然后在 Spider 中通过创建一个 Processor来执行首页中所有一级链接的抓起，但是我该如何将这些抓到的一级链接拿到后直接放到一个新的 Spider 中执行新的抓取任务呢？

        还请不吝赐教，给一些最佳实践的灵感，谢谢。

**Comment by zlzforever** [comment]
有很多方式。你可以分开写2个爬虫，第一个爬虫的数据入到数据库中，第二个爬虫的起始链接从数据库中获取，可以参考https://github.com/dotnetcore/DotnetSpider/blob/master/src/DotnetSpider.Sample/docs/DbStartUrlsBuilderSpider.cs

第二种方式可以是写在一个爬虫里，每个processor是可以通过正则来匹配处理的链接的。

**Comment by hippieZhou** [comment]
@zlzforever ,谢谢
