### ISSUE TITLE
如何在Linux、MacOS下使用vscode和dotnet命令行成功运行？

### ISSUE THREAD

**Issue by lljxww** [dotnetcore/DotnetSpider#61]
在项目的.shproj文件中发现有一些依赖visualstudio的引用项。
水平有限，不知道如何去掉有关的依赖。

**Comment by zlzforever** [comment]
用vscode或者rider或者dotnet命令应该都是没有问题的。在centos下可以通过dotnet build DotnetSpider.sln编译项目。

**Comment by lljxww** [comment]
@zlzforever 克隆下来项目后 直接cd到目录下，运行dotnet build DotnetSpider.sln，结果如下：
<img width="840" alt="2018-07-02 22 21 38" src="https://user-images.githubusercontent.com/12098363/42169444-55812f5a-7e46-11e8-972e-37e1ba2f3d45.png">

**Comment by zlzforever** [comment]
1. 确保您的代码是最新的
2. 确保您的SDK 2.1以上
我这边MAC是好的
<img width="532" alt="qq20180703-221825 2x" src="https://user-images.githubusercontent.com/3038592/42225655-a28e1190-7f0f-11e8-9c20-ac4958999791.png">
