### ISSUE TITLE
如何模拟用户登录

### ISSUE THREAD

**Issue by 715476864** [dotnetcore/DotnetSpider#62]
如题！请问框架如何模拟用户登录。

**Comment by 715476864** [comment]
我需要爬取的内容需要用户登录。我尝试采用Post请求的方式去登录，始终不能成功，贴上代码，请大神指点指点：

class Program
  {
        static void Main(string[] args)
        {
            SpiderStart();
            Console.WriteLine("按任意键退出……");
            Console.Read();
        }

        /// <summary>
        /// 启动爬虫
        /// </summary>
        public static void SpiderStart()
        {
            var site = new Site { EncodingName = "UTF-8", RemoveOutboundLinks = false };           
            site.AddStartUrl(@"http://xxxx.xxx.xxx/");//http://xxxx.xxx.xxx是登录页面
            Spider spider = Spider.Create(site, new NewsPageProcessor()).AddPipeline(new NewsPipline());
            spider.Downloader = new HttpClientDownloader();
            spider.Downloader.AddAfterDownloadCompleteHandler(new OpenNewsAfterDownloaderHandler());
            spider.Downloader.AddBeforeDownloadHandler(new OpenNewsBeforeDownloadHandler());
            spider.ThreadNum = 1;
            spider.EmptySleepTime = 3000;
            
            spider.Run();
        }


        /// <summary>
        /// 定义要爬取的数据
        /// </summary>
        public class NewsData
        {
            /// <summary>
            /// 新闻标题
            /// </summary>
            public string NewsTitle { get; set; }

            /// <summary>
            /// 新闻日期
            /// </summary>
            public string NewsDate { get; set; }

            /// <summary>
            /// 新闻地址
            /// </summary>
            public string Url { get; set; }

            /// <summary>
            /// 新闻内容
            /// </summary>
            public string Content { get; set; }
        }


        /// <summary>
        /// 下载页面之前
        /// </summary>
        public class OpenNewsBeforeDownloadHandler : BeforeDownloadHandler
        {
            public override void Handle(ref Request request, IDownloader downloader, ISpider spider)
            {
            }
        }

        /// <summary>
        /// 页面下载完成时
        /// </summary>
        public class OpenNewsAfterDownloaderHandler : AfterDownloadCompleteHandler
        {
            public override void Handle(ref Page page, IDownloader downloader, ISpider spider)
            {
                var cookies = downloader.GetCookies(page.Request.Uri);
               //这里始终获取不到返回的Cookie值，是方式错了吗？？？？
            }
        }
        /// <summary>
        /// 页面解析
        /// </summary>
        public class NewsPageProcessor : BasePageProcessor
        {
            protected override void Handle(Page page)
            {
                if (page.Url == @"http://xxxx.xxx.xxx/")
                {                    
                    List<NewsData> results = new List<NewsData>();
                    results.Add(new NewsData()
                    {
                        NewsTitle = "忽略",
                        NewsDate = DateTime.Now.ToShortDateString(),
                        Url = ""
                    });
                    page.AddResultItem("NewsList", results);
                    
                    Request request = new Request();
                    request.Url = @"http://xxxx.xxx.xxx/user/login";//登录地址
                    request.Method = HttpMethod.Post;
                    request.PostBody = JsonConvert.SerializeObject(new
                    {
                        username = "admin",
                        password = "admin123456"
                    });
                    page.AddTargetRequest(request);
                }
            }
        }

        /// <summary>
        /// 数据处理
        /// </summary>
        public class NewsPipline : BasePipeline
        {
            public override void Process(IEnumerable<ResultItems> resultItems, ISpider spider)
            {
                foreach (var resultItem in resultItems)
                {
                    foreach (NewsData newsData in resultItem.Results["NewsList"])
                    {                        
                        Console.WriteLine(string.Format("{0} {1} {2}", newsData.NewsTitle, newsData.NewsDate, newsData.Url));
                    }
                }
            }
        }
 }

不知道模拟用户登录是不是采用这种方式，还是框架有其他的方式？？
用户登录成功返回的授权信息又如何获取呢？？？
搞了两天了，不知道如何解决了，大神帮帮忙啊。

**Comment by zlzforever** [comment]
我这几天没空。稍等几天吧

**Comment by zlzforever** [comment]
所为登录？服务器如何状态你是登录状态？依靠cookie或者header等，所以模拟登录就是注入cookie的过程。如果被采集服务器对cookie没有特别的处理，反爬你可以使用fiddler自己截取一段登录后的COOKIE写到爬虫里即可。如果要不定时重新登录，则实现一个CookieInjector即可
