### ISSUE TITLE
headers 中添加了 cookie 但是请求头中始终没有携带

### ISSUE THREAD

**Issue by hanxiaomin** [dotnetcore/DotnetSpider#64]
var site = new Site
            {
                CycleRetryTimes = 1,
                SleepTime = 200,
                Headers = new Dictionary<string, string>()
                {
                    { "Accept","*/*" },
                    { "Referer", "https://ad.tt.com/login/"},
                    { "Cookie","tt_webid=6582711285758166536" },
                    { "Connection","keep-alive" },
                    { "Content-Type","application/x-www-form-urlencoded" },
                    { "User-Agent","Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"}
                }
            };

**Comment by xljiulang** [comment]
默认的，HttpClientHandler的UseCookies为True，Cookie由CookieContainer维护，所以写到请求头的Cookie会被忽略，应该写入关联的CookieContainer；

**Comment by hanxiaomin** [comment]
非常抱歉，第一次用dotnetspider, 应该怎么去关联CookieContainer呢？
