### ISSUE TITLE
能否将文档更新为DotnetSpider.Core

### ISSUE THREAD

**Issue by yedajiang44** [dotnetcore/DotnetSpider#65]
首先感谢开源此库，在看了issues后我发现DotnetSpider.Core2并不是最新版的，于是改为DotnetSpider.Core，但是我发现所有的文档都是DotnetSpider.Core2的，而且DotnetSpider.Core的注释没有DotnetSpider.Core2的完整。。。

**Comment by zlzforever** [comment]
原因是最早我想上传到nuget时，发现package id：dotnetspider被人占用了, 在找不到上传者的情况下只能使用DotnetSpider2这样的前缀。偶然在今年又找到了占用者，经联系他把dotnetspider的权限给到我，所以后面的更新都是在dotnetspider系列下面了。
dotnetspider刚刚进行一次大的重构，把各个组件解藕，这样即使不是dotnetspider用户也可以单独使用如下载器，HTML解析这样的库。所以在文档上没什么更新，如果你要使用，建议直接参考：DotnetSpider.Sample.docs下面所有的示例。如有其它问题，可以进群。

**Comment by wakuflair** [comment]
@zlzforever 你好。
我能不能理解现在nuget上dotnetspider就是最新的package？不用再安装dotnetspider2了？
