### ISSUE TITLE
两个Pipeline取数据取不到的问题

### ISSUE THREAD

**Issue by Simluzifer** [dotnetcore/DotnetSpider#66]
JsonFileEntityPipeline中第66行，直接取entry.ToString()返回不了数据。
![json](https://user-images.githubusercontent.com/7322301/43452519-3a1c8f24-94ea-11e8-9add-18dc135a180d.png)

ExcelEntityPipeline中第95行，data[column]返回不了数据，因为data是实体类。
![excel](https://user-images.githubusercontent.com/7322301/43452593-607736e2-94ea-11e8-8891-1688b72d78d0.png)

**Comment by zlzforever** [comment]
FIXED
