### ISSUE TITLE
更新数据模式优化, 不以主键为条件

### ISSUE THREAD

**Issue by zlzforever** [dotnetcore/DotnetSpider#69]

**Comment by phoenixzero** [comment]
//使用mysql数据库更新实体数据时发现无法更新
` AddPipeline(new MySqlEntityPipeline("Data Source = localhost; User ID = root; Password =XXXXXX; Port = 3306; SslMode = None;",PipelineMode.Update));`
//实体部分
```
`           [Column]
            [Unique]
            [Field(Expression = "lianjiaid", Type = SelectorType.Enviroment)]
            public string Lianjiaid { get; set; }
```
```

            [Column]
            [Update]
            [Field(Expression = ".//lng", Type = SelectorType.XPath)]
            public string Longitude { get; set; }

            [Column]
            [Update]
            [Field(Expression = ".//lat", Type = SelectorType.XPath)]
            public string Latitude { get; set; }`
```

**Comment by phoenixzero** [comment]
BaseEntity中将Id设置为了主键，导致在更新数据时自己设置的[primary]无法被正确识别为主键（因为Dotnetspider生成update语句时自动回把id加上形成类似于//"update XXX.XXX set some = @some where myPrimary = @myPrimary and id = @Id"）

**Comment by zlzforever** [comment]
这是一个使用问题，BaseEntity只是一个通用的实现，你可以不继承它。然后自己定义自己的主键
