### ISSUE TITLE
Can this scrape javascript? Also what is this based on?

### ISSUE THREAD

**Issue by majestique** [dotnetcore/DotnetSpider#70]
I've a few questions - can dotnetspider scrape:
1. Javascript? How does this compare to scrapy?
2. Whole tables in one line?

**Comment by zlzforever** [comment]
It's not a language or framework different. In essence, crawler is send http request and receive text( html or json). That means if you can construct correct request, any framework/language can scrape what you want. When a website use javascript to load data, you need to figure out where is the data from? Some times the data(json) is hard code in the html, and always the data is called by ajax, so you can use Fiddler to capture the request and construct correct request: cookie, headers, post body etc...
Sometimes, the URL you want to request may contains a token, then you need to reverse javascript, there is a easy way to skip reverse javascript, use WebDriverDownloader, it's like you use brower/js engine.
I don't know what's the mean your second question.
Hope this is helpful.

**Comment by majestique** [comment]
Thank you, it doesn't really parse data just requests and receives the data via http.
