### ISSUE TITLE
NuGet-Packages

### ISSUE THREAD

**Issue by blafa** [dotnetcore/DotnetSpider#71]
Hi
I have a question regarding NuGet-Packages. Which Project are intended to be a Nuget-Package? Only Dotnetspider.Core?
Best
f

**Comment by zlzforever** [comment]
Please use DotnetSpider.*  packages. Those DotnetSpider2.* packages are old, long times ago somebody used DotnetSpider.* IDs, after two years i find that guy and he give the owner permission of DotnetSpider.* to me

**Comment by blafa** [comment]
Thx. But the two important Packages are .Core and .Extension, right?

**Comment by zlzforever** [comment]
Yes

**Comment by blafa** [comment]
thx
