### ISSUE TITLE
自带Sample运行有问题

### ISSUE THREAD

**Issue by sPhinX-LHJ** [dotnetcore/DotnetSpider#74]
是因为现在DotnetSpider库的更新太快了吗？导致自带Sample都跟不上步子了？

AfterDownloadCompleteHandlerSpider Sample运行起来之后
			protected override void OnInit(params string[] arguments)
			{
				AddRequest($"http://api.search.sina.com.cn/?c=news&t=&q=赵丽颖&pf=2136012948&ps=2130770082&page=0&stime={DateTime.Now.AddYears(-7).AddDays(-1).ToString("yyyy-MM-dd")}&etime={DateTime.Now.AddDays(1).ToString("yyyy-MM-dd")}&sort=rel&highlight=1&num=10&ie=utf-8&callback=jQuery1720001955628746606708_1508996230766&_=1508996681484", new Dictionary<string, dynamic> { { "keyword", "赵丽颖" } });
				AddPipeline(new ConsoleEntityPipeline());
				Downloader.AddAfterDownloadCompleteHandler(new ReplaceHandler());
				AddEntityType<SinaNews>();
			}

Downloader是null，导致运行出错，能更新下Sample吗？

**Comment by zlzforever** [comment]
好的

**Comment by zlzforever** [comment]
已修复
