### ISSUE TITLE
求文档和案例

### ISSUE THREAD

**Issue by crashsol** [dotnetcore/DotnetSpider#77]
没得文档。。用起来好痛苦，案例好像也没完整，大佬整整

**Comment by newlifes01** [comment]
主要还是新版和老版还使用不一样的方法。

**Comment by yang-xiaodong** [comment]
不要急，等抽出来时间会完善的

**Comment by zlzforever** [comment]
我还在做些别的事情，如果你们有写文档的兴趣我可以视频教你们怎么用，你们整理成文档。单靠我个人的力量还是太薄弱了

**Comment by HappyGis520** [comment]
是有点乱啊，都不知道怎么用了！来来，我来整理文档

**Comment by HappyGis520** [comment]
这编译都不通过了，现在是用的什么环境啊？

**Comment by crashsol** [comment]
请问直接获取Json或则Content内容的爬虫怎么弄呢，参照文章3没有弄成功

**Comment by zlzforever** [comment]
@HappyGis520 travis都过了怎么可能编译不过。dotnet core sdk装到最新, VS2017即可

**Comment by TTonlyV5** [comment]
这案例看的头大，不连贯，新手表示好难。。。

**Comment by HappyGis520** [comment]
> @HappyGis520 travis都过了怎么可能编译不过。dotnet core sdk装到最新, VS2017即可

更新到最新版 就可以了

**Comment by WXinFfly** [comment]
实现分布式的案例在哪个文件里？

**Comment by ashuai** [comment]
没文档好难过。我爬到list的item url后，怎么进到item的url继续取得field呢？谢谢

**Comment by zlzforever** [comment]
@ashuai 实现2个Processor，通过匹配让不同的URL进入到不同的Processor, LIST的解析生成新的 REQUEST加到TargetRequest中，就会进入下载队列

**Comment by WXinFfly** [comment]
怎么指定代理和Cookie是一个呢？

**Comment by lawrence-peng** [comment]
如果业务场景是一个实时查询的爬虫，比较好的实践是不是，每次查询都去 spider.create 呢？谢谢

**Comment by zlzforever** [comment]
还是要结合你具体的需求。不过最新的版本我已经把各个组件拆开了，已经没有耦合关系了。就是说Downlowder你可以独立使用, 解析库Extraction, Pipeline都可以自己组合。当然你得熟悉一下...  最近很忙没时间搞文档

**Comment by lawrence-peng** [comment]
我举个例子，就像支付宝里的信用卡还款里管理账单，支付宝要管理账单，首先要录入自己的邮箱号与密码让支付宝去账单的邮箱去爬。像类似这样场景一般都是属于实时爬取的场景的。

**Comment by williamreg** [comment]
虽然框架很好还开源，但没有文档（过期文档没用），暂时还是算了。
有文档再来看看。

**Comment by harry7988** [comment]
新手案例感觉好跳跃，不连贯，，，求更新！

**Comment by snow611** [comment]
新手 求文档！！！用起来好吃力啊！

**Comment by guojq2com** [comment]
感觉有点乱，自己摘一部分代码，自己修改一下使用吧，

**Comment by tiger2014** [comment]
求文档

**Comment by itotaku-tm** [comment]
请问下：我爬取多个网站，配置多个url以及对应的Processor。调试的时候发现，每一个url都会去匹配一次Processor。这种情况效率很慢，能不能让一个url就只是对应一个Processor？
是我的写法有问题，还是有办法进行解决呢？

**Comment by AGDholo** [comment]
没文档真的好难

**Comment by stone111111** [comment]
拷贝里面的代码，引入包，结果到处都是错

**Comment by stone111111** [comment]
又无法找到老版本引入，玩不下去了

**Comment by 407249209** [comment]
文档弄的乱七八糟的，真心不知道该怎么用！群里问也得不到什么答案

**Comment by siegrainwong** [comment]
目前文档、Sample、Nuget包还是割裂的- -

**Comment by siegrainwong** [comment]
sample跑不通的可以尝试一下最新版本nuget package，稍微改一下应该能跑
```cs
Install-Package DotnetSpider -Version 4.0.8-beta5
```
