### ISSUE TITLE
爬取全站数据时报Uri错误

### ISSUE THREAD

**Issue by SunYork** [dotnetcore/DotnetSpider#80]
![image](https://user-images.githubusercontent.com/17267443/47842456-a2a23480-ddf7-11e8-8e4c-9269b0638446.png)
错误原因在request里面，希望作者看一下。

**Comment by zlzforever** [comment]
是有一些url不符合uri规范吗？

**Comment by SunYork** [comment]
是的

**Comment by zlzforever** [comment]
能举例子说明某些URL即不符合URI规范，但实际上又是你需要下载的吗？如果确认不需要难URI，你可以修改一个PR提交上来

**Comment by zlzforever** [comment]
新版不对URL做URI校验了
