### ISSUE TITLE
两个关于DbRequestBuilder的错误

### ISSUE THREAD

**Issue by lvhua6352** [dotnetcore/DotnetSpider#81]
在使用DbRequestBuilder类的过程中遇到了两个错误，作者可以确认一下：
1. 在QueryDatas方法中，这一句`var dataItem = item as Dictionary<string, dynamic>`转换失败，返回为空，解决方法：改为`var dataItem = (item as IDictionary<string, dynamic>).ToDictionary(kvp => kvp.Key, kvp => kvp.Value)`
2. Build方法调用之后并没有把生成的Request加入_requests里面
![1](https://user-images.githubusercontent.com/16402961/48312365-6a190c80-e5e8-11e8-9eea-c0cb21a1397f.png)

**Comment by lvhua6352** [comment]
我看到最新的代码里对类名和方法名有一些修改，但问题应该还是存在

**Comment by zlzforever** [comment]
感谢, 已 FIX
