### ISSUE TITLE
关于DefaultProxyValidator的问题

### ISSUE THREAD

**Issue by lvhua6352** [dotnetcore/DotnetSpider#82]
我是从网上爬的免费代理，在执行这句代码验证的时候 `var host = Dns.GetHostEntry(httpProxy.Host)`，绝大部分的代理都会抛出异常，但其实大部分代理都是能用的。可以考虑改一下验证的方式，比如直接用代理访问这个网站`http://httpbin.org/ip`
![tempsnip](https://user-images.githubusercontent.com/16402961/48418039-39270c00-e78f-11e8-8005-340584175fa7.png)

**Comment by zlzforever** [comment]
可否告知是什么异常呢？如果你有时间，可以提交一个 Http 的难证方法，就是直接用被检测代理访问如baidu.com这样的网站。但要注意的是 每一个代理都要消耗一个端口，如果太多不可用的代理，容易把本机端口耗尽。

**Comment by lvhua6352** [comment]
基本上是这两种异常：
System.Net.Sockets.SocketException: 不知道这样的主机。
System.Net.Sockets.SocketException: 这是在主机名解析时通常出现的暂时错误，它意味着本地服务器没有从权威服务器上收到响应。
另外现在这样使用socket去连接，也是每个代理都要用一个端口吧？

**Comment by sanjusss** [comment]
在不同的实际项目中，需求各有不同，建议自行实现IHttpProxyPool、IProxyValidator、IProxySupplier。
例如通过 [https://httpbin.org/ip](https://httpbin.org/ip)验证代理：
```
    public class HttpBinProxyValidator : IProxyValidator
    {
        private readonly string _targetUrl;

        public HttpBinProxyValidator(string targetUrl = "https://httpbin.org/ip")
        {
            _targetUrl = targetUrl;
        }

        public bool IsAvailable(WebProxy proxy)
        {
            if (proxy == null)
            {
                throw new ArgumentNullException(nameof(proxy));
            }

            try
            {
                var handler = new HttpClientHandler
                {
                    AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip,
                    UseProxy = true,
                    UseCookies = true,
                    AllowAutoRedirect = true,
                    Proxy = proxy,
                };

                using (HttpClient client = new HttpClient(handler, true))
                {
                    client.Timeout = new TimeSpan(0, 0, 5);
                    string json = client.GetStringAsync(_targetUrl).Result;
                    var obj = JObject.Parse(json);
                    string origin = obj["origin"].ToString();
                    return string.IsNullOrEmpty(origin) == false && origin.IndexOf(',') == -1;
                }
            }
            catch
            {
                return false;
            }
        }
    }
```  
这个验证器的性能取决于你调用的频率和逻辑，尽量减少同时验证线程数量和频率。如果条件允许，你可以单独用一台服务器来验证代理池中的代理是否可用，然后把可用地址发送到工作服务器/组。

**Comment by lvhua6352** [comment]
> 在不同的实际项目中，需求各有不同，建议自行实现IHttpProxyPool、IProxyValidator、IProxySupplier。
> 例如通过 https://httpbin.org/ip验证代理：
> 
> ```
>     public class HttpBinProxyValidator : IProxyValidator
>     {
>         private readonly string _targetUrl;
> 
>         public HttpBinProxyValidator(string targetUrl = "https://httpbin.org/ip")
>         {
>             _targetUrl = targetUrl;
>         }
> 
>         public bool IsAvailable(WebProxy proxy)
>         {
>             if (proxy == null)
>             {
>                 throw new ArgumentNullException(nameof(proxy));
>             }
> 
>             try
>             {
>                 var handler = new HttpClientHandler
>                 {
>                     AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip,
>                     UseProxy = true,
>                     UseCookies = true,
>                     AllowAutoRedirect = true,
>                     Proxy = proxy,
>                 };
> 
>                 using (HttpClient client = new HttpClient(handler, true))
>                 {
>                     client.Timeout = new TimeSpan(0, 0, 5);
>                     string json = client.GetStringAsync(_targetUrl).Result;
>                     var obj = JObject.Parse(json);
>                     string origin = obj["origin"].ToString();
>                     return string.IsNullOrEmpty(origin) == false && origin.IndexOf(',') == -1;
>                 }
>             }
>             catch
>             {
>                 return false;
>             }
>         }
>     }
> ```
> 这个验证器的性能取决于你调用的频率和逻辑，尽量减少同时验证线程数量和频率。如果条件允许，你可以单独用一台服务器来验证代理池中的代理是否可用，然后把可用地址发送到工作服务器/组。
嗯

**Comment by lvhua6352** [comment]
> 在不同的实际项目中，需求各有不同，建议自行实现IHttpProxyPool、IProxyValidator、IProxySupplier。
> 例如通过 https://httpbin.org/ip验证代理：
> 
> ```
>     public class HttpBinProxyValidator : IProxyValidator
>     {
>         private readonly string _targetUrl;
> 
>         public HttpBinProxyValidator(string targetUrl = "https://httpbin.org/ip")
>         {
>             _targetUrl = targetUrl;
>         }
> 
>         public bool IsAvailable(WebProxy proxy)
>         {
>             if (proxy == null)
>             {
>                 throw new ArgumentNullException(nameof(proxy));
>             }
> 
>             try
>             {
>                 var handler = new HttpClientHandler
>                 {
>                     AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip,
>                     UseProxy = true,
>                     UseCookies = true,
>                     AllowAutoRedirect = true,
>                     Proxy = proxy,
>                 };
> 
>                 using (HttpClient client = new HttpClient(handler, true))
>                 {
>                     client.Timeout = new TimeSpan(0, 0, 5);
>                     string json = client.GetStringAsync(_targetUrl).Result;
>                     var obj = JObject.Parse(json);
>                     string origin = obj["origin"].ToString();
>                     return string.IsNullOrEmpty(origin) == false && origin.IndexOf(',') == -1;
>                 }
>             }
>             catch
>             {
>                 return false;
>             }
>         }
>     }
> ```
> 这个验证器的性能取决于你调用的频率和逻辑，尽量减少同时验证线程数量和频率。如果条件允许，你可以单独用一台服务器来验证代理池中的代理是否可用，然后把可用地址发送到工作服务器/组。

嗯  谢谢
