### ISSUE TITLE
有没有增加 Cookie 池 与 UserAgent 池设计的计划

### ISSUE THREAD

**Issue by lawrence-peng** [dotnetcore/DotnetSpider#84]
有没有增加 Cookie 池 与 UserAgent 池设计的计划

**Comment by zlzforever** [comment]
可以讨论一下在现在的反爬技术体系下, UA 池的作用还有多少？ Cookie现在是支持自己切换的

**Comment by lawrence-peng** [comment]
我是爬虫开发新手，没有办法给很有建议性的意见，至于 Cookie 池网上都在说，我的理解不知道对不对，就像 Proxy 池一样，有自己维护的能力，如果 Cookie 还有效，就不去申请

**Comment by zlzforever** [comment]
如果你要自实现也不是很难。框架里有CookieInject的接口，你可以自己实现一个从数据库取cookie的接口就可以。在afterdownloaderhandler判断是否要注入新的cookie
