### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mcicekci** [dotnetcore/DotnetSpider#87]
Hello there,
Dotnetspider good. Net crawler.
But I need documents.
I want to use it, but I don't know how to install and configure it.

**Comment by zlzforever** [comment]
@wolverine81 hi, there is a sample project and a lot of example in docs folder. you can have a try to read them. I don't have enough time to write document until 1 month later. sry

**Comment by yang-xiaodong** [comment]
Duplicate of #77
