### ISSUE TITLE
项目中的Serilog日志如果通过appsettings.json或者xml来配置？

### ISSUE THREAD

**Issue by jeraytang** [dotnetcore/DotnetSpider#88]
项目中的Serilog日志如果通过appsettings.json或者xml来配置？
请教下生产环境如果控制日志级别路径等问题？

**Comment by zlzforever** [comment]
@jeraytang 你好，之前并没有考虑到这个需求。如果你真的觉得这个是个非常必要的功能。可以把AppBase里的 _loggerFactory开放成public property, 然后这样，你就可以在外面添加自己想要的任何日志扩展组件了。需要注意的是，在run方法里，要判断如果loggerFactory为空，则使用我原来的默认初始化为serilog即可。完成后可以提交PR给我。感谢。后期我可能会考虑全部使用微软DI的方式来使用，方便各种扩展。最近1个月没有什么 时间

**Comment by jeraytang** [comment]
好的，感谢感谢！
