### ISSUE TITLE
AutoIncrementRequestExtractor, Start HomePage

### ISSUE THREAD

**Issue by mehmetkurt** [dotnetcore/DotnetSpider#90]
Hello there,

I've just started a new review. I really like. Thank you so much.

I have a question!

I had problems with repeated queries when I wanted to crawl a single site. For example, I've added an AutoIncrementRequestExtractor instance to the OneForAllSpider instance. But the Extractor didn't work because it started from the main page. How can I solve this?

Thank you from now.

**Comment by zlzforever** [comment]
Could you show your codes?
