### ISSUE TITLE
大量数据持续写入数据库时，写入效率逐渐变低

### ISSUE THREAD

**Issue by sanjusss** [dotnetcore/DotnetSpider#93]
现在代码中，对每个ResultItems中的每个List建立一个数据库连接，然后执行操作。然而：
- 对于一个数据库来说，同时建立的连接是有限的。
- 一个数据连接关闭后，数据库要等待一段时间才释放相关资源。
- 同时写入一张表时，会自动加锁，挂起相关连接。

现有代码中建立大量数据库连接的方式会导致数据库的连接池中可用连接逐渐变少，大量写入线程挂起，写入效率逐渐降低。（我最近有个爬虫项目保存数据在MySql上，开始是写入是7000条/分钟，过了2天后，写入速度降低至2000条/分钟，数据库的cpu基本是80~100%）  

我想出一个办法来解决这类问题：  
重写EntityPipeline和DbEntityPipeline，加入“异步写入”的选项。当这个选项开启时，所有待写入的数据汇总到一个独立的“数据库更新线程”中的缓存中。“数据库更新线程”每隔一段时间（1秒或小于1秒，取决于上次写入所用的时间），用事务操作的方式，将所有缓存数据写入到数据库中。  

用这个办法，我现在已经为MySql单独写了一个基于BasePipeline的异步写入类，运行两天后，写入速度保持在7000条/分钟，数据库的CPU使用率在20%以下。

如果可以的话，我将在下周一前，提交修改后的EntityPipeline和DbEntityPipeline。

**Comment by sanjusss** [comment]
我上面说的办法有个缺点，异步写入数据库，将不会返回每个请求影响数据库的行数。

**Comment by zlzforever** [comment]
Spider中有CacheSize设置，一次批量提交数据

**Comment by sanjusss** [comment]
> Spider中有CacheSize设置，一次批量提交数据

[EntityPipeline.Process](https://github.com/dotnetcore/DotnetSpider/blob/master/src/DotnetSpider.Extension/Pipeline/EntityPipeline.cs)中为每个`ResultItems`中的每个类型的`List<IBaseEntity>`调用[DbEntityPipeline.Process](https://github.com/dotnetcore/DotnetSpider/blob/master/src/DotnetSpider.Extension/Pipeline/DbEntityPipeline.cs)。相当于每有一个`List<IBaseEntity>`调用一次`DbEntityPipeline.RefreshConnectionString`，建立一次到数据库的连接。根据代码来看，`DbEntityPipeline.RefreshConnectionString`调用的时间是和`CacheSize`有关的，但次数是无关的。正因为创建了过多的数据库连接，才导致数据库性能降低的。我的想法是尽量降低数据库连接频率，从而减少数据库使用读写锁频率和连接挂起时间。

**Comment by libaili-dev** [comment]
同意@sanjuss说的

**Comment by zlzforever** [comment]
@sanjusss 我其实还不能判断到底是哪里导致的。我们从头分析一下：
cachedsize是多个页面(可能是不同类型的页面，对应不能的entity)->大多情况下只有一个entity->因此配置了cachedsize实际就是缓存了多个页面数据一次性提交到了db process处理 -> RefreshConnectString，在final里有dispose操作，实际的释放是有pool管理的。另外，你说2天后写入性能变慢，是否有查看连接数？机器环境是什么，有没有可能是云服器超卖或者单表数据量太大导致的？

**Comment by zlzforever** [comment]
现在存储可以配置是否使用事务
