### ISSUE TITLE
协程酒店价格是javascript加了密的, 用浏览器开发工具找不到相关内容,能不能用dotnetspider解析出来

### ISSUE THREAD

**Issue by swpuzhang** [dotnetcore/DotnetSpider#95]

**Comment by zlzforever** [comment]
爬虫框架是模拟HTTP请求下载数据，解析数据，入库存储数据。并不是说可以帮你自动破解别人加密的API。理解上就有偏差。如果实在没有能力破解的话，尝试使用webdriver直接操纵浏览器去下载HTML

**Comment by swpuzhang** [comment]
有些python爬虫框架可以解析js, 获取执行js后的页面, 我只是问下这个框架有没有这个功能. 我对C#熟悉点, 想用C#作爬虫

**Comment by zlzforever** [comment]
PY也是调用selenium， .NET下用webdriver, 框架已经有实现的webdriverdownloader
