### ISSUE TITLE
spider 中怎么使用http代理

### ISSUE THREAD

**Issue by landonzeng** [dotnetcore/DotnetSpider#96]
看了源码，还是不太清楚如何使用
在自己代码里这样写的，但是跑不起来，其中123.115.120.182:9000是代理ip地址和端口
`

public static void Run()
        {
            WebProxy webProxy = new WebProxy();
            webProxy.Address = new Uri("http://123.115.120.182:9000");
            ProxyInfo proxyInfo = new ProxyInfo(webProxy);
            ProxySupplier p = new ProxySupplier(proxyInfo);
            HttpProxyPool.Instance = new HttpProxyPool(p);
            List<BuildInfo> buildInfoList = new List<BuildInfo>();
            List<UnitInfo> untiInfoList = new List<UnitInfo>();
            int sleep = Convert.ToInt32(JsonConfigurationHelper.GetAppSettings("ThreadNum", "SleepTime"));
            using (var conn = new SqlConnection(Env.DataConnectionString))
            {
                buildInfoList = conn.Query<BuildInfo>("SELECT Building_Id FROM T_UnitInfo WITH(NOLOCK) WHERE ISNULL(Building_Id,'')!='' GROUP BY Building_Id").ToList();
                untiInfoList = conn.Query<UnitInfo>("SELECT Unit_Id FROM T_UnitInfo WITH(NOLOCK) WHERE ISNULL(Unit_Id,'')!='' GROUP BY Unit_Id").ToList();
            }
            BuildInfoSpider spider = new BuildInfoSpider(buildInfoList, untiInfoList, sleep);
            var threadNum = JsonConfigurationHelper.GetAppSettings("ThreadNum", "Number");
            spider.ThreadNum = Convert.ToInt32(threadNum);
            spider.CycleRetryTimes = 5;
            spider.Run();
        }

`

**Comment by gonemad4u** [comment]
我也是，普通的request我就是这么加的proxy，不知道用dotnetspider怎么加

HttpWebRequest Request = (HttpWebRequest)WebRequest.Create("https://www.baidu.com");
WebProxy myproxy = new WebProxy("ssvpxy20", 8080);
myproxy.BypassProxyOnLocal = false;
Request.Proxy = myproxy;
Request.Credentials = CredentialCache.DefaultCredentials;
Request.Proxy.Credentials = CredentialCache.DefaultCredentials;

**Comment by sanjusss** [comment]
仅针对我发帖时的3.0.8版（3.x版本略有不同）
要使用代理，需要将下载器HttpClientDownloader的UseProxy属性设置成true、HttpProxyPool属性设置为代理池的实例。
由于设置的固定代理，你需要重新实现IHttpProxyPool接口，使其GetProxy无限制可以返回固定值。

**Comment by landonzeng** [comment]
@sanjusss 能提供个demo吗？

**Comment by Interopnl** [comment]
Could someone please provide some code examples on howto implement a custom IProxySupplier?

Thanks in advanced!

**Comment by zlzforever** [comment]
Sorry for the delay, if you want to use proxy, i suggest you to checout refactory-5.0 branch. There are lot s of update for use proxy.

A lots of proxy provider support WEB API to get proxies, and it return data like:
x.x.x.x:8080
y.y.y.y:8181

I impl a KuaidailiProxySupplier in the  refactory-5.0 branch

**Comment by hurui79** [comment]
还是没明白应该怎么用http代理，有列子么？
