### ISSUE TITLE
HttpClientDownloader类中，“哪些类型的内容不需要当成文件下载”判断结果总为false

### ISSUE THREAD

**Issue by kasnti** [dotnetcore/DotnetSpider#97]
HttpClientDownloader类中第130行，
MediaType判断是否包含ExcludeMediaTypes内的值，不论MediaType为何值，

`if (!ExcludeMediaTypes.Any(t => httpResponseMessage.Content.Headers.ContentType.MediaType.Contains(t)))`

if内的结果总为false

原因是ExcludeMediaTypes中有个项是`""`，任何非空字符串都包含`""`，所以判断结果永远是false。

linq语句中改为
`t => t.Contains(httpResponseMessage.Content.Headers.ContentType.MediaType)`就ok了

**Comment by sanaeslami94** [comment]
Hi, this was weird for me too. It seems StorageFile() Function is unreachable and unused. 
The problem is that I can’t change the code because I’m using DLLs of DotnetSpider ( using nugget package).and I need to download content. 
Any help?

**Comment by sanaeslami94** [comment]
Can i actually download anything except text and json? 
I need to save webpage for offline use. any help guys?

**Comment by blinkybill** [comment]
Hi Lewis, if I wish to for example both download a HTML file, and process it (to find other links and so on) how is this possible given this variable is readonly? Is there a different way download of these files is intended to happen?

public readonly List<string> ExcludeMediaTypes = new List<string>
		{
			"",
			"text/html",
			"text/plain",
			"text/richtext",
			"text/xml",
			"text/XML",
			"text/json",
			"text/javascript",
			"application/soap+xml",
			"application/xml",
			"application/json",
			"application/x-javascript",
			"application/javascript",
			"application/x-www-form-urlencoded"
		};

**Comment by zlzforever** [comment]
@blinkybill @sanaeslami94 i remove this exclude rule. the new design is downloader download byte[] then send byte[] to message queue,  spider's parser will handle the response, so every can customize your parser logic to do any thing

**Comment by sanaeslami94** [comment]
Great job. My problem is solved completely with this new design.
I appreciate this.
