### ISSUE TITLE
One or more errors occurred. (The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by h0730303779** [dotnetcore/DotnetSpider#99]
sdk 2.2
爬虫版本 2.5.1
系统 centos 7.2 
爬虫无法工作  503  异常信息:
One or more errors occurred. (The SSL connection could not be established, see inner exception

是否和这个问题 同样的 _https://github.com/dotnet/corefx/issues/30623_
如果是该如何处理
window 平台 正常

![image](https://user-images.githubusercontent.com/16299810/50544803-3fd4ea00-0c3c-11e9-9fd7-8554e59c2428.png)

-----

Sdk 2.2
Reptile version 2.5.1
System centos 7.2
The crawler is not working. 503 Exception information :
One or more errors occurred. (The SSL connection could not be established, see inner exception
Is it the same as this question?   _https://github.com/dotnet/corefx/issues/30623_
If it is how to deal with it
Window platform normal

**Comment by zlzforever** [comment]
我无法判断是什么问题。我自己这边centos暂未发现问题
